#!/usr/bin/env python3
"""Integer reference twin of fw/wsola_core.h (Cymo C7, B-549): the fixed-point WSOLA tempo core, written independently in plain Python integers.

Why it exists: the firmware core (C, no floating point, rv32im) must give exactly the same samples as an independent implementation of the same integer
algorithm, the same discipline as the JS twins of the meter modules and the golden models of the RTL cores. sim/test_wsola.py runs both on the same input and
requires identical output. The float model (tools/lab/cymo_tempo_model.py) stays the quality reference; this file is the bit-exact contract.

The algorithm (every constant is shared with the C header; change both together):
  Rates >= 32 kHz: coarse decimation DEC = 8, grain N = 1024, hop Hs = 512; below: DEC = 4, N = 512 (the grain is about 23 ms either way).
  The search is +-delta_c = 55 coarse samples (about 10 ms), then +-DEC samples at the full rate over a 256-sample window.
  Coarse signal: the mono mix (L+R)>>1, summed over DEC samples and shifted right by log2(DEC).
  Correlation inputs are scaled by a per-search right shift so the reference peaks at <= 1023 and clamped to +-2047, which keeps every sum inside int32.
  The best candidate maximises num*num/en (first maximum wins), only num > 0 counts; with no positive correlation (silence) the nominal position is used.
  The grain is overlap-added with a Q15 Hann window at 50% overlap: out = (prev_tail*(32768-w) + grain_head*w + 16384) >> 15, where the two weights sum to
  32768 exactly, so there is no gain error and no clipping.
Usage: this module is imported by the test; `python3 tools/lab/wsola_fixed_ref.py --emit-header` prints fw/wsola_tables.h.
"""
import math
import sys

REF_LEN = 256
DELTA_C = 55
Q15 = 32768


def hann_q15():
    """The rising half of a periodic Hann window of length 1024, Q15: w[i] = round(32768 * (0.5 - 0.5 cos(2 pi i / 1024))), i = 0..511."""
    return [int(math.floor(Q15 * (0.5 - 0.5 * math.cos(2.0 * math.pi * i / 1024.0)) + 0.5)) for i in range(512)]


def emit_header():
    t = hann_q15()
    rows = []
    for i in range(0, 512, 16):
        rows.append("    " + ", ".join("%5d" % v for v in t[i:i + 16]) + ",")
    return ("/* GENERATED by tools/lab/wsola_fixed_ref.py --emit-header (Cymo C7, B-549). Do not edit.\n"
            " * Rising half of a periodic Hann window of length 1024 in Q15: w[i] = round(32768 * (0.5 - 0.5 cos(2 pi i / 1024))), i = 0..511.\n"
            " * The falling half is 32768 - w[i], so two overlapping grains sum to exactly unity. A 512-sample grain uses every second entry. */\n"
            "#ifndef WSOLA_TABLES_H\n#define WSOLA_TABLES_H\n#include <stdint.h>\n"
            "#ifndef WS_DATA\n#define WS_DATA\n#endif\n"
            "static const uint16_t ws_hann_q15[512] WS_DATA = {\n" + "\n".join(rows) + "\n};\n#endif\n")


class Wsola:
    def __init__(self, fs, ch, speed_q8):
        speed_q8 = max(128, min(768, speed_q8))        # 0.5x .. 3.0x, as in the C core
        self.fs, self.ch, self.speed_q8 = fs, ch, speed_q8
        if fs >= 32000:
            self.dec, self.shift, self.N = 8, 3, 1024
        else:
            self.dec, self.shift, self.N = 4, 2, 512
        self.Hs = self.N // 2
        self.nc = self.N // self.dec
        self.delta = DELTA_C * self.dec
        self.k = 0
        self.prev = 0
        self.p_q8 = self.Hs * speed_q8
        self.pend = [[0] * self.Hs for _ in range(ch)]
        self.macs = 0
        self.w = hann_q15()

    # ---- helpers -------------------------------------------------------------------------------------------------------------------------------------
    def _mix(self, x, i):
        if self.ch == 2:
            return (x[0][i] + x[1][i]) >> 1
        return x[0][i]

    def _geometry(self):
        tgt = self.prev + self.Hs
        p = (self.p_q8 + 128) >> 8
        lo_c = (p - self.delta) // self.dec if p > self.delta else 0
        hi_c = (p + self.delta) // self.dec
        return tgt, p, lo_c, hi_c

    def need(self):
        """(lo, hi): the absolute sample range the next step reads."""
        if self.k == 0:
            return 0, self.N
        tgt, p, lo_c, hi_c = self._geometry()
        lo_a = (lo_c * self.dec - self.dec) if lo_c > 0 else 0
        lo = min((tgt // self.dec) * self.dec, lo_a)   # the coarse reference starts at the decimation boundary at or below tgt
        hi = max(tgt + self.N, hi_c * self.dec + self.dec + self.N)
        return lo, hi

    @staticmethod
    def _scale(vals):
        m = max((abs(v) for v in vals), default=0)
        s = 0
        while (m >> s) > 1023:
            s += 1
        return s

    @staticmethod
    def _search(ref, cand, ncand, n):
        """Best start in cand[0 .. ncand) for ref of length n. Returns (index or -1, macs). cand has ncand + n - 1 entries (already scaled and clamped)."""
        refen = sum(v * v for v in ref)
        if refen == 0:
            return -1, 0
        en = sum(v * v for v in cand[0:n])
        best, best_s, macs = -1, -1, 0
        for c in range(ncand):
            if c > 0:
                a, b = cand[c - 1], cand[c + n - 1]
                en += b * b - a * a
            num = 0
            for i in range(n):
                num += ref[i] * cand[c + i]
            macs += n
            score = (num * num) // (en if en > 0 else 1) if num > 0 else 0
            if score > best_s:
                best_s, best = score, c
        return (best if best_s > 0 else -1), macs

    # ---- one grain -----------------------------------------------------------------------------------------------------------------------------------
    def step(self, x):
        """x[ch] is the whole input (absolute indexing). Returns Hs samples per channel."""
        ch, N, Hs = self.ch, self.N, self.Hs
        if self.k == 0:
            out = [list(x[c][0:Hs]) for c in range(ch)]
            for c in range(ch):
                self.pend[c] = list(x[c][Hs:N])
            self.prev = 0
            self.k = 1
            return out
        dec = self.dec
        tgt, p, lo_c, hi_c = self._geometry()
        # coarse: decimated mono mix over the reference and every candidate window
        j0 = min(lo_c, tgt // dec)
        j1 = max(hi_c + self.nc, tgt // dec + self.nc)
        xd = {}
        for j in range(j0, j1):
            s = 0
            for i in range(dec):
                s += self._mix(x, j * dec + i)
            xd[j] = s >> self.shift
        ref = [xd[tgt // dec + i] for i in range(self.nc)]
        sc = self._scale(ref)
        ref = [v >> sc for v in ref]
        ncand = hi_c - lo_c + 1
        cand = [max(-2047, min(2047, xd[lo_c + i] >> sc)) for i in range(ncand + self.nc - 1)]
        idx, m1 = self._search(ref, cand, ncand, self.nc)
        cd = lo_c + idx if idx >= 0 else max(lo_c, min(hi_c, p // dec))
        # refine at the full rate
        c0 = cd * dec
        rlo = c0 - dec if c0 > dec else 0
        rhi = c0 + dec
        nref = rhi - rlo + 1
        mix = [self._mix(x, rlo + j) for j in range(nref + REF_LEN - 1)]
        rf = [self._mix(x, tgt + i) for i in range(REF_LEN)]
        s2 = self._scale(rf)
        rf = [v >> s2 for v in rf]
        cd2 = [max(-2047, min(2047, v >> s2)) for v in mix]
        idx2, m2 = self._search(rf, cd2, nref, REF_LEN)
        c = rlo + idx2 if idx2 >= 0 else c0
        self.macs += m1 + m2
        # overlap-add the grain
        step = 1 if N == 1024 else 2
        out = []
        for chn in range(ch):
            g = x[chn][c:c + N]
            o = []
            for i in range(Hs):
                w = self.w[i * step]
                o.append((self.pend[chn][i] * (Q15 - w) + g[i] * w + 16384) >> 15)
            out.append(o)
            self.pend[chn] = list(g[Hs:N])
        self.prev = c
        self.p_q8 += self.Hs * self.speed_q8
        self.k += 1
        return out


def run(x, fs, speed_q8):
    """Process the whole input (x is a list of channels). Returns (output channels, macs, grains)."""
    ch = len(x)
    ws = Wsola(fs, ch, speed_q8)
    n = len(x[0])
    outs = [[] for _ in range(ch)]
    while True:
        lo, hi = ws.need()
        if hi > n:
            break
        o = ws.step(x)
        for c in range(ch):
            outs[c].extend(o[c])
    return outs, ws.macs, ws.k


if __name__ == "__main__":
    if "--emit-header" in sys.argv:
        sys.stdout.write(emit_header())
    else:
        print(__doc__)
