#!/usr/bin/env python3
"""Integer reference twin of fw/wsola_core.h (Cymo C7, B-549): the fixed-point WSOLA tempo core, written independently in plain Python integers.

Why it exists: the firmware core (C, no floating point, rv32im) must give exactly the same samples as an independent implementation of the same integer
algorithm, the same discipline as the JS twins of the meter modules and the golden models of the RTL cores. sim/test_wsola.py runs both on the same input and
requires identical output. The float model (tools/lab/cymo_tempo_model.py) stays the quality reference; this file is the bit-exact contract.

The algorithm (every constant is shared with the C header; change both together):
  Rates >= 32 kHz: grain N = 1024, hop Hs = 512, stage decimations D1 = 32 and D2 = 8; below: N = 512, D1 = 16, D2 = 4 (the grain is about 23 ms either way).
  Three-stage search (B-550; the single coarse stage of B-549 cost 4x as many multiply-adds for no better quality, see tools/lab/wsola_search_lab.py):
    1. coarse: +-14 candidates (units of D1, about +-10 ms) around the nominal position, window N/D1 = 32 samples;
    2. middle: +-4 candidates (units of D2) around stage 1's winner, window N/D2 = 128 samples;
    3. fine:   +-D2 samples at the full rate around stage 2's winner, window 128 samples.
  Mono mix = (L+R)>>1. A stage-2 sample is the sum of D2 mixes shifted right by log2(D2); a stage-1 sample is the sum of 4 stage-2 samples shifted right by 2, so the
  input is decimated once and the coarse signal is derived from it.
  Correlation inputs are scaled by a per-search right shift so the reference peaks at <= 1023 and clamped to +-2047, which keeps every sum inside int32.
  The best candidate maximises num*num/en (first maximum wins), only num > 0 counts; with no positive correlation (silence) the stage's centre is used.
  The grain is overlap-added with a Q15 Hann window at 50% overlap: out = (prev_tail*(32768-w) + grain_head*w + 16384) >> 15, where the two weights sum to
  32768 exactly, so there is no gain error and no clipping.
Usage: this module is imported by the test; `python3 tools/lab/wsola_fixed_ref.py --emit-header` prints fw/wsola_tables.h.
"""
import math
import sys

REF_LEN = 128
R1 = 14          # stage-1 radius in candidates
R2 = 4           # stage-2 radius in candidates
Q15 = 32768


def hann_q15():
    """The rising half of a periodic Hann window of length 1024, Q15: w[i] = round(32768 * (0.5 - 0.5 cos(2 pi i / 1024))), i = 0..511."""
    return [int(math.floor(Q15 * (0.5 - 0.5 * math.cos(2.0 * math.pi * i / 1024.0)) + 0.5)) for i in range(512)]


def emit_header():
    t = hann_q15()
    rows = []
    for i in range(0, 512, 16):
        rows.append("    " + ", ".join("%5d" % v for v in t[i:i + 16]) + ",")
    return ("/* GENERATED by tools/lab/wsola_fixed_ref.py --emit-header (Cymo C7, B-549). Do not edit.\n"
            " * Rising half of a periodic Hann window of length 1024 in Q15: w[i] = round(32768 * (0.5 - 0.5 cos(2 pi i / 1024))), i = 0..511.\n"
            " * The falling half is 32768 - w[i], so two overlapping grains sum to exactly unity. A 512-sample grain uses every second entry. */\n"
            "#ifndef WSOLA_TABLES_H\n#define WSOLA_TABLES_H\n#include <stdint.h>\n"
            "#ifndef WS_DATA\n#define WS_DATA\n#endif\n"
            "static const uint16_t ws_hann_q15[512] WS_DATA = {\n" + "\n".join(rows) + "\n};\n#endif\n")


class Wsola:
    def __init__(self, fs, ch, speed_q8):
        speed_q8 = max(128, min(768, speed_q8))        # 0.5x .. 3.0x, as in the C core
        self.fs, self.ch, self.speed_q8 = fs, ch, speed_q8
        if fs >= 32000:
            self.D1, self.D2, self.shift, self.N = 32, 8, 3, 1024
        else:
            self.D1, self.D2, self.shift, self.N = 16, 4, 2, 512
        self.Hs = self.N // 2
        self.nc1 = self.N // self.D1
        self.nc2 = self.N // self.D2
        self.k = 0
        self.prev = 0
        self.p_q8 = self.Hs * speed_q8
        self.pend = [[0] * self.Hs for _ in range(ch)]
        self.macs = 0
        self.w = hann_q15()

    # ---- helpers -------------------------------------------------------------------------------------------------------------------------------------
    def _mix(self, x, i):
        if self.ch == 2:
            return (x[0][i] + x[1][i]) >> 1
        return x[0][i]

    def _xd2(self, x, j):
        s = 0
        for i in range(self.D2):
            s += self._mix(x, j * self.D2 + i)
        return s >> self.shift

    def _geometry(self):
        tgt = self.prev + self.Hs
        p = (self.p_q8 + 128) >> 8
        c1 = p // self.D1
        lo1 = c1 - R1 if c1 > R1 else 0
        hi1 = c1 + R1
        e0 = lo1 * 4 - 4 if lo1 * 4 > 4 else 0           # first stage-2 sample of the candidate region
        e1 = hi1 * 4 + 4 + self.nc2                        # one past its last
        return tgt, p, c1, lo1, hi1, e0, e1

    def need(self):
        """(lo, hi): the absolute sample range the next step reads."""
        if self.k == 0:
            return 0, self.N
        tgt, p, c1, lo1, hi1, e0, e1 = self._geometry()
        rb = (tgt // self.D1) * self.D1                    # the reference region starts on the coarse grid at or below tgt
        lo = min(rb, e0 * self.D2)
        hi = max(rb + (self.nc2 + 3) * self.D2, e1 * self.D2, (hi1 * 4 + 4) * self.D2 + self.D2 + self.N)
        return lo, hi

    @staticmethod
    def _scale(vals):
        m = max((abs(v) for v in vals), default=0)
        s = 0
        while (m >> s) > 1023:
            s += 1
        return s

    @staticmethod
    def _search(ref, cand, ncand, n):
        """Best start in cand[0 .. ncand) for ref of length n. Returns (index or -1, macs). cand has ncand + n - 1 entries (already scaled and clamped)."""
        refen = sum(v * v for v in ref)
        if refen == 0:
            return -1, 0
        en = sum(v * v for v in cand[0:n])
        best, best_s, macs = -1, -1, 0
        for c in range(ncand):
            if c > 0:
                a, b = cand[c - 1], cand[c + n - 1]
                en += b * b - a * a
            num = 0
            for i in range(n):
                num += ref[i] * cand[c + i]
            macs += n
            score = (num * num) // (en if en > 0 else 1) if num > 0 else 0
            if score > best_s:
                best_s, best = score, c
        return (best if best_s > 0 else -1), macs

    # ---- one grain -----------------------------------------------------------------------------------------------------------------------------------
    def step(self, x):
        """x[ch] is the whole input (absolute indexing). Returns Hs samples per channel."""
        ch, N, Hs = self.ch, self.N, self.Hs
        if self.k == 0:
            out = [list(x[c][0:Hs]) for c in range(ch)]
            for c in range(ch):
                self.pend[c] = list(x[c][Hs:N])
            self.prev = 0
            self.k = 1
            return out
        D1, D2, nc1, nc2 = self.D1, self.D2, self.nc1, self.nc2
        tgt, p, c1, lo1, hi1, e0, e1 = self._geometry()
        # the reference: stage-2 samples from the coarse grid at or below tgt (nc2 + 3 of them), the stage-1 reference derived from them
        rbase = (tgt // D1) * 4
        R = [self._xd2(x, rbase + i) for i in range(nc2 + 3)]
        ref1 = [(R[4 * i] + R[4 * i + 1] + R[4 * i + 2] + R[4 * i + 3]) >> 2 for i in range(nc1)]
        sc1 = self._scale(ref1)
        ref1 = [v >> sc1 for v in ref1]
        # the candidate region at the stage-2 rate, and the stage-1 candidates derived from it
        C = [self._xd2(x, e0 + i) for i in range(e1 - e0)]
        ncand1 = hi1 - lo1 + 1
        cand1 = []
        for i in range(ncand1 + nc1 - 1):
            b = 4 * (lo1 + i) - e0
            cand1.append(max(-2047, min(2047, ((C[b] + C[b + 1] + C[b + 2] + C[b + 3]) >> 2) >> sc1)))
        idx1, m1 = self._search(ref1, cand1, ncand1, nc1)
        w1 = lo1 + idx1 if idx1 >= 0 else max(lo1, min(hi1, c1))
        # stage 2
        c2 = w1 * 4
        lo2 = c2 - 4 if c2 > 4 else 0
        ncand2 = c2 + 4 - lo2 + 1
        off2 = (tgt // D2) - rbase
        ref2 = R[off2:off2 + nc2]
        sc2 = self._scale(ref2)
        ref2 = [v >> sc2 for v in ref2]
        cand2 = [max(-2047, min(2047, C[lo2 - e0 + i] >> sc2)) for i in range(ncand2 + nc2 - 1)]
        idx2, m2 = self._search(ref2, cand2, ncand2, nc2)
        w2 = lo2 + idx2 if idx2 >= 0 else c2
        # fine, at the full rate over +-D2 samples
        c0 = w2 * D2
        rlo = c0 - D2 if c0 > D2 else 0
        nref = c0 + D2 - rlo + 1
        mix = [self._mix(x, rlo + j) for j in range(nref + REF_LEN - 1)]
        rf = [self._mix(x, tgt + i) for i in range(REF_LEN)]
        s3 = self._scale(rf)
        rf = [v >> s3 for v in rf]
        cd3 = [max(-2047, min(2047, v >> s3)) for v in mix]
        idx3, m3 = self._search(rf, cd3, nref, REF_LEN)
        c = rlo + idx3 if idx3 >= 0 else c0
        self.macs += m1 + m2 + m3
        # overlap-add the grain
        step = 1 if N == 1024 else 2
        out = []
        for chn in range(ch):
            g = x[chn][c:c + N]
            o = []
            for i in range(Hs):
                w = self.w[i * step]
                o.append((self.pend[chn][i] * (Q15 - w) + g[i] * w + 16384) >> 15)
            out.append(o)
            self.pend[chn] = list(g[Hs:N])
        self.prev = c
        self.p_q8 += self.Hs * self.speed_q8
        self.k += 1
        return out


class Wsola2(Wsola):
    """Core v2 (B-556): the same algorithm, restructured. The input is decimated once, as it is fed, into a ring of RING entries (the stage-2-rate mono mix, entry j
    = the mix of samples j*D2 .. j*D2+D2-1, summed and shifted); the stage-1 signal is derived from four ring entries as before; the full-rate samples the fine stage and
    the grain need come through a reader `rd(ch, lo, n)` instead of a window. Output is identical to Wsola's, sample for sample; written separately from the C."""
    RING = 1024

    def __init__(self, fs, ch, speed_q8):
        super().__init__(fs, ch, speed_q8)
        self.ring = [0] * self.RING
        self.fed = 0
        self.acc = 0
        self.cnt = 0

    def feed(self, chans, lo, n):
        """Feed samples lo .. lo+n-1 of every channel (in order)."""
        for i in range(lo, lo + n):
            self.acc += (chans[0][i] + chans[1][i]) >> 1 if self.ch == 2 else chans[0][i]
            self.cnt += 1
            if self.cnt == self.D2:
                self.ring[(self.fed // self.D2) % self.RING] = self.acc >> self.shift
                self.acc = 0
                self.cnt = 0
            self.fed += 1

    def ready(self):
        lo, hi = self.need()
        if self.fed < hi:
            return False
        if self.k == 0:
            return True
        tgt, p, c1, lo1, hi1, e0, e1 = self._geometry()
        first = min((tgt // self.D1) * 4, e0)
        return (self.fed // self.D2) - first <= self.RING

    def step2(self, rd):
        ch, N, Hs, D2, nc1, nc2 = self.ch, self.N, self.Hs, self.D2, self.nc1, self.nc2
        if self.k == 0:
            out = [rd(c, 0, Hs) for c in range(ch)]
            for c in range(ch):
                self.pend[c] = rd(c, Hs, Hs)
            self.prev = 0
            self.k = 1
            return out
        E = lambda j: self.ring[j % self.RING]
        tgt, p, c1, lo1, hi1, e0, e1 = self._geometry()
        rbase = (tgt // self.D1) * 4
        ref1 = [(E(rbase + 4 * i) + E(rbase + 4 * i + 1) + E(rbase + 4 * i + 2) + E(rbase + 4 * i + 3)) >> 2 for i in range(nc1)]
        sc1 = self._scale(ref1)
        ref1 = [v >> sc1 for v in ref1]
        ncand1 = hi1 - lo1 + 1
        cand1 = []
        for i in range(ncand1 + nc1 - 1):
            b = 4 * (lo1 + i)
            cand1.append(max(-2047, min(2047, ((E(b) + E(b + 1) + E(b + 2) + E(b + 3)) >> 2) >> sc1)))
        idx1, m1 = self._search(ref1, cand1, ncand1, nc1)
        w1 = lo1 + idx1 if idx1 >= 0 else max(lo1, min(hi1, c1))
        c2 = w1 * 4
        lo2 = c2 - 4 if c2 > 4 else 0
        ncand2 = c2 + 4 - lo2 + 1
        ref2 = [E(tgt // D2 + i) for i in range(nc2)]
        sc2 = self._scale(ref2)
        ref2 = [v >> sc2 for v in ref2]
        cand2 = [max(-2047, min(2047, E(lo2 + i) >> sc2)) for i in range(ncand2 + nc2 - 1)]
        idx2, m2 = self._search(ref2, cand2, ncand2, nc2)
        w2 = lo2 + idx2 if idx2 >= 0 else c2
        c0 = w2 * D2
        rlo = c0 - D2 if c0 > D2 else 0
        nref = c0 + D2 - rlo + 1
        nm = nref + REF_LEN - 1
        if ch == 2:
            mix = [(a + b) >> 1 for a, b in zip(rd(0, rlo, nm), rd(1, rlo, nm))]
            rf = [(a + b) >> 1 for a, b in zip(rd(0, tgt, REF_LEN), rd(1, tgt, REF_LEN))]
        else:
            mix, rf = rd(0, rlo, nm), rd(0, tgt, REF_LEN)
        s3 = self._scale(rf)
        rf = [v >> s3 for v in rf]
        cd3 = [max(-2047, min(2047, v >> s3)) for v in mix]
        idx3, m3 = self._search(rf, cd3, nref, REF_LEN)
        cg = rlo + idx3 if idx3 >= 0 else c0
        self.macs += m1 + m2 + m3
        step = 1 if N == 1024 else 2
        out = []
        for chn in range(ch):
            first = rd(chn, cg, Hs)
            out.append([(self.pend[chn][i] * (Q15 - self.w[i * step]) + first[i] * self.w[i * step] + 16384) >> 15 for i in range(Hs)])
            self.pend[chn] = rd(chn, cg + Hs, Hs)
        self.prev = cg
        self.p_q8 += self.Hs * self.speed_q8
        self.k += 1
        return out


def run2(x, fs, speed_q8, chunk=64):
    """Feed `chunk` samples at a time and step whenever ready. Returns (output channels, macs, grains, overran) where overran means the ring lost data the next
    step needed (the caller fed too much between steps)."""
    ch = len(x)
    ws = Wsola2(fs, ch, speed_q8)
    n = len(x[0])
    outs = [[] for _ in range(ch)]
    rd = lambda c, lo, m: list(x[c][lo:lo + m])
    pos = 0
    overran = False
    while pos < n:
        m = min(chunk, n - pos)
        ws.feed(x, pos, m)
        pos += m
        while ws.ready():
            o = ws.step2(rd)
            for c in range(ch):
                outs[c].extend(o[c])
        lo, hi = ws.need()
        if ws.fed >= hi and not ws.ready():
            overran = True
            break
    return outs, ws.macs, ws.k, overran


def run(x, fs, speed_q8):
    """Process the whole input (x is a list of channels). Returns (output channels, macs, grains)."""
    ch = len(x)
    ws = Wsola(fs, ch, speed_q8)
    n = len(x[0])
    outs = [[] for _ in range(ch)]
    while True:
        lo, hi = ws.need()
        if hi > n:
            break
        o = ws.step(x)
        for c in range(ch):
            outs[c].extend(o[c])
    return outs, ws.macs, ws.k


if __name__ == "__main__":
    if "--emit-header" in sys.argv:
        sys.stdout.write(emit_header())
    else:
        print(__doc__)
