#ifndef BP_NFRAMES
#define BP_NFRAMES 90
#endif
/* Shared by the two Winamp Bars pack harnesses (sim/bars_pack_native.c: the meter compiled straight in; tools/host/pack_harness.c with -DPACK_BARS: the meter loaded as a pack
 * and run under rv32sim). The same deterministic input trace is generated by the same code on both sides and every draw command (rectangle or bar) is hashed in order, so
 * equal hashes mean the pack draws exactly what the built-in meter draws. Needs meter.h, meters_gen.h (the parameter indices). */
static uint32_t bp_rs;
static uint32_t bp_rnd(void) { bp_rs = bp_rs * 1664525u + 1013904223u; return bp_rs >> 8; }
static uint64_t bp_H; static uint32_t bp_N;
static void bp_mix(const uint32_t *v, int n) { for (int i = 0; i < n; i++) { bp_H ^= v[i]; bp_H *= 1099511628211ull; } bp_N++; }
static void bp_hash_rect(uint32_t x, uint32_t y, uint32_t w, uint32_t h, uint16_t c) { const uint32_t v[6] = { 1, x, y, w, h, c }; bp_mix(v, 6); }
static void bp_hash_bar(uint32_t x, uint32_t y, uint32_t w, uint32_t h, uint32_t lit, uint16_t fg, uint16_t bg) { const uint32_t v[8] = { 2, x, y, w, h, lit, fg, bg }; bp_mix(v, 8); }

/* params: the live setting values; force: the repaint flag the meter clears; run: the meter's tick. Four scenarios: the defaults; fewer bands without peak caps; a spring ease with
 * a different release; and the defaults with the box resized and moved mid-run (a new geometry must repaint everything). */
static void bars_trace(uint16_t *params, uint8_t *force, uint32_t (*run)(const mtr_in_t *), void (*report)(int scen, uint32_t n, uint64_t h))
{
    uint16_t base[MP_WINAMP_BARS_N];
    for (uint32_t i = 0; i < MP_WINAMP_BARS_N; i++) base[i] = params[i];
    for (int s = 0; s < 4; s++) {
        for (uint32_t i = 0; i < MP_WINAMP_BARS_N; i++) params[i] = base[i];
        if (s == 1) { params[MP_WINAMP_BARS_BANDS] = 8; params[MP_WINAMP_BARS_PEAK_ON] = 0; }
        if (s == 2) { params[MP_WINAMP_BARS_BANDS] = 12; params[MP_WINAMP_BARS_EASE] = 3; params[MP_WINAMP_BARS_RELEASE] = 40; params[MP_WINAMP_BARS_PEAK_FALL] = 60; }
        bp_rs = 4242u + (uint32_t)s; bp_H = 1469598103934665603ull; bp_N = 0;
        *force = 1;
        for (int n = 0; n < BP_NFRAMES; n++) {
            uint8_t spec[16]; int8_t wave[64];
            const int quiet = (n >= 40 && n < 50);
            for (int i = 0; i < 16; i++) spec[i] = quiet ? 0 : (uint8_t)((bp_rnd() % 256u) * (16u - (uint32_t)i / 2u) / 16u);
            for (int i = 0; i < 64; i++) wave[i] = 0;
            mtr_in_t in; for (unsigned k = 0; k < sizeof in; k++) ((uint8_t *)&in)[k] = 0;
            in.paused = (uint8_t)(n >= 20 && n < 26); in.spec = spec; in.wave = wave; in.force = (uint8_t)(n == 0 || n == 30); in.dt_ms = 26u;
            in.bg = 0x18C3u;
            in.x = 16; in.y = 152; in.w = 368; in.h = 122;
            if (s == 3 && n >= 60) { in.x = 8; in.w = 300; in.h = 100; }       /* a new geometry without a forced repaint */
            if (n == 30) *force = 1;
            run(&in);
        }
        report(s, bp_N, bp_H);
    }
}
