/* Shared by the two Layered Wave pack harnesses (sim/lw_pack_native.c: the meter compiled straight in; tools/host/pack_harness.c: the meter loaded as a pack
 * and run under rv32sim). The same deterministic input trace is generated by the same code on both sides and every draw command is hashed in order, so
 * equal hashes mean the pack draws exactly what the built-in meter draws. Needs meter.h, meters_gen.h (the parameter indices) and a printf-like out(). */
static uint32_t lw_rs;
static uint32_t lw_rnd(void) { lw_rs = lw_rs * 1664525u + 1013904223u; return lw_rs >> 8; }
static uint64_t lw_H; static uint32_t lw_N;
static void lw_hash_rect(uint32_t x, uint32_t y, uint32_t w, uint32_t h, uint16_t c)
{
    const uint32_t v[5] = { x, y, w, h, c };
    for (int i = 0; i < 5; i++) { lw_H ^= v[i]; lw_H *= 1099511628211ull; }
    lw_N++;
}

/* params: the live setting values (the meter reads them); force: the repaint flag the meter clears; run: the meter's tick. */
static void lw_trace(uint16_t *params, uint8_t *force, uint32_t (*run)(const mtr_in_t *), void (*report)(int scen, uint32_t n, uint64_t h))
{
    uint16_t base[MP_LAYERED_WAVE_N];
    for (uint32_t i = 0; i < MP_LAYERED_WAVE_N; i++) base[i] = params[i];
    for (int s = 0; s < 3; s++) {
        for (uint32_t i = 0; i < MP_LAYERED_WAVE_N; i++) params[i] = base[i];
        if (s == 1) { params[MP_LAYERED_WAVE_LAYERS] = 6; params[MP_LAYERED_WAVE_RES] = 200; params[MP_LAYERED_WAVE_DRAW] = 1; }
        if (s == 2) { params[MP_LAYERED_WAVE_SPLIT] = 2; params[MP_LAYERED_WAVE_COLOR_MODE] = 1; }
        lw_rs = 777u + (uint32_t)s; lw_H = 1469598103934665603ull; lw_N = 0;
        *force = 1;
        for (int n = 0; n < 48; n++) {
            uint8_t spec[16]; int8_t wave[64];
            const int quiet = (n >= 30 && n < 36);
            for (int i = 0; i < 16; i++) spec[i] = quiet ? 0 : (uint8_t)((lw_rnd() % 256u) * (16u - (uint32_t)i / 2u) / 16u);
            for (int i = 0; i < 64; i++) wave[i] = quiet ? 0 : (int8_t)((int)(lw_rnd() % 201u) - 100);
            mtr_in_t in; for (unsigned k = 0; k < sizeof in; k++) ((uint8_t *)&in)[k] = 0;
            in.paused = (uint8_t)(n >= 20 && n < 26); in.spec = spec; in.wave = wave; in.force = (uint8_t)(n == 0 || n == 24); in.dt_ms = 26u;
            in.x = 16; in.y = 152; in.w = 368; in.h = 122;
            if (n == 24) *force = 1;
            run(&in);
        }
        report(s, lw_N, lw_H);
    }
}
