#ifndef SP_NFRAMES
#define SP_NFRAMES 90
#endif
/* Shared by the two Winamp Scope pack harnesses (sim/scope_pack_native.c: the meter compiled straight in; tools/host/pack_harness.c with -DPACK_SCOPE: the meter loaded as a pack
 * and run under rv32sim). The same deterministic input trace is generated by the same code on both sides; every rectangle, background restore, background blend (its result
 * alternates, so both the trail and the erase fallback run) and diagnostics note is hashed in order, so equal hashes mean the pack draws and calls exactly what the built-in does. */
static uint32_t sp_rs;
static uint32_t sp_rnd(void) { sp_rs = sp_rs * 1664525u + 1013904223u; return sp_rs >> 8; }
static uint64_t sp_H; static uint32_t sp_N, sp_blend_calls;
static void sp_mix(const uint32_t *v, int n) { for (int i = 0; i < n; i++) { sp_H ^= v[i]; sp_H *= 1099511628211ull; } sp_N++; }
static void sp_hash_rect(uint32_t x, uint32_t y, uint32_t w, uint32_t h, uint16_t c) { const uint32_t v[6] = { 1, x, y, w, h, c }; sp_mix(v, 6); }
static void sp_hash_restore(uint32_t x, uint32_t y, uint32_t w, uint32_t h) { const uint32_t v[5] = { 2, x, y, w, h }; sp_mix(v, 5); }
static int  sp_hash_blend(uint32_t x, uint32_t y, uint32_t w, uint32_t h, uint32_t a) { const uint32_t v[6] = { 3, x, y, w, h, a }; sp_mix(v, 6); return (int)(sp_blend_calls++ % 3u != 2u); }
static void sp_hash_note(int ok, uint32_t x, uint32_t y) { const uint32_t v[4] = { 4, (uint32_t)ok, x, y }; sp_mix(v, 4); }

/* Scenarios: 0 player screen (gradient, trail 30); 1 flat background (the Configure preview) with trail 0 and smoothing 0; 2 fullscreen (per-column erase) with heavy smoothing;
 * 3 player screen with the box moved mid-run and a quiet stretch. grad/fullscreen are set through the pointers the harness passes. */
static void scope_trace(uint16_t *params, uint8_t *force, uint8_t *grad, uint8_t *fullscreen, uint32_t (*run)(const mtr_in_t *), void (*report)(int scen, uint32_t n, uint64_t h))
{
    uint16_t base[MP_WINAMP_SCOPE_N];
    for (uint32_t i = 0; i < MP_WINAMP_SCOPE_N; i++) base[i] = params[i];
    for (int s = 0; s < 4; s++) {
        for (uint32_t i = 0; i < MP_WINAMP_SCOPE_N; i++) params[i] = base[i];
        *grad = (s == 1) ? 0u : 1u; *fullscreen = (s == 2) ? 1u : 0u; sp_blend_calls = 0;
        if (s == 1) { params[MP_WINAMP_SCOPE_SCOPE_SMOOTH] = 0; params[MP_WINAMP_SCOPE_SCOPE_TRAIL] = 0; }
        if (s == 2) { params[MP_WINAMP_SCOPE_SCOPE_SMOOTH] = 80; params[MP_WINAMP_SCOPE_SCOPE_TRAIL] = 50; }
        sp_rs = 777u + (uint32_t)s; sp_H = 1469598103934665603ull; sp_N = 0;
        *force = 1;
        for (int n = 0; n < SP_NFRAMES; n++) {
            int8_t wave[64]; uint8_t spec[16];
            const int quiet = (s == 3 && n >= 40 && n < 50);
            for (int i = 0; i < 64; i++) wave[i] = quiet ? 0 : (int8_t)((int)(sp_rnd() % 201u) - 100);
            if (s == 0 && n >= 60) for (int i = 0; i < 64; i++) wave[i] = (int8_t)(i < 32 ? 100 : -100);    /* a clipped square wave: the clamps */
            for (int i = 0; i < 16; i++) spec[i] = 0;
            mtr_in_t in; for (unsigned k = 0; k < sizeof in; k++) ((uint8_t *)&in)[k] = 0;
            in.paused = (uint8_t)(n >= 20 && n < 26); in.spec = spec; in.wave = wave; in.force = (uint8_t)(n == 0 || n == 30); in.dt_ms = 26u;
            in.bg = 0x18C3u;
            in.x = 16; in.y = 152; in.w = 368; in.h = 122;
            if (s == 3 && n >= 60) { in.x = 8; in.w = 300; in.h = 100; }
            if (n == 30) *force = 1;
            run(&in);
        }
        report(s, sp_N, sp_H);
    }
}
