#!/usr/bin/env python3
"""B-567: the embedded-cover decoder (fw/art.inc + picojpeg) on real firmware code under tools/rv32sim.py.

Wraps each JPEG in sim/fixtures/art/ (generated by sim/gen_art_fixtures.py) as an ID3v2.3 APIC frame and as a FLAC
PICTURE block, runs the real art_sig_of() and art_decode() through tools/host/art_decode_harness.c, and requires:
  - the return code, failure code and the FNV hash of the 128x128 stash to equal sim/fixtures/art/golden.json
    (recorded from the decoder BEFORE its buffers were moved out of hot RAM, B-567);
  - the same result when every buffer that may live in uninitialised PSRAM is poisoned with junk before the decode
    (a second build with -DPOISON=1), so nothing relies on those buffers starting at zero or keeping old content;
  - the MP3 and FLAC wrappers of one image decode to the same stash;
  - the progressive JPEG fails identically every time (picojpeg is baseline only).
  python3 sim/test_art_decode.py --update-golden   rewrites the golden file (only on purpose)."""
import json
import re
import struct
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIX = ROOT / "sim" / "fixtures" / "art"
BUILD = ROOT / "build" / "art_decode"
GCC = ROOT / "toolchain/xpack-riscv-none-elf-gcc-15.2.0-1/bin/riscv-none-elf-gcc"


def syncsafe(n):
    return bytes([(n >> 21) & 127, (n >> 14) & 127, (n >> 7) & 127, n & 127])


def wrap_id3(jpg):
    body = b"\x00image/jpeg\x00\x03\x00" + jpg
    frame = b"APIC" + struct.pack(">I", len(body)) + b"\x00\x00" + body
    return b"ID3\x03\x00\x00" + syncsafe(len(frame)) + frame + b"\xff\xfb\x90\x00" * 8


def wrap_flac(jpg):
    mime = b"image/jpeg"
    body = (struct.pack(">II", 3, len(mime)) + mime + struct.pack(">I", 0) + struct.pack(">IIII", 300, 300, 24, 0)
            + struct.pack(">I", len(jpg)) + jpg)
    return b"fLaC" + bytes([0, 0, 0, 34]) + bytes(34) + bytes([0x80 | 6]) + len(body).to_bytes(3, "big") + body


def build(poison):
    BUILD.mkdir(parents=True, exist_ok=True)
    elf = BUILD / ("harness_poison.elf" if poison else "harness.elf")
    cmd = [str(GCC), "-march=rv32im", "-mabi=ilp32", "-mno-relax", "-Os", "-ffreestanding", "-nostdlib", "-nostartfiles",
           "-Wall", "-Wextra", "-Wno-unused-function", "-Wno-shift-negative-value", "-Wno-unused-parameter",
           "-I", str(ROOT / "tools/host"), "-I", str(ROOT / "third_party/picojpeg"), "-Wl,--no-warn-rwx-segments",
           "-T", str(ROOT / "tools/host/link.ld"), str(ROOT / "tools/host/start.S"),
           str(ROOT / "tools/host/art_decode_harness.c"), "-o", str(elf)]
    if poison:
        cmd.insert(1, "-DPOISON=1")
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        print(r.stdout, r.stderr)
        sys.exit("harness build failed")
    return elf


def run(elf, blob):
    f = BUILD / "blob.bin"
    f.write_bytes(blob)
    r = subprocess.run([sys.executable, str(ROOT / "tools/rv32sim.py"), str(elf), str(f)], capture_output=True, text=True)
    m = re.search(r"rc=(\d+) fail=(\d+) hash=0x([0-9A-Fa-f]+) sig=0x([0-9A-Fa-f]+)", r.stdout)
    if not m:
        print(r.stdout, r.stderr)
        sys.exit("harness produced no result")
    return {"rc": int(m[1]), "fail": int(m[2]), "hash": m[3].lower(), "sig": m[4].lower()}


def main():
    update = "--update-golden" in sys.argv
    jpgs = sorted(FIX.glob("*.jpg"))
    assert jpgs, "no fixtures: run sim/gen_art_fixtures.py"
    elf, elf_p = build(False), build(True)
    golden_path = FIX / "golden.json"
    golden = {} if update or not golden_path.exists() else json.loads(golden_path.read_text())
    got, fails = {}, 0

    def check(cond, msg):
        nonlocal fails
        print(("ok   " if cond else "FAIL ") + msg)
        fails += not cond

    for j in jpgs:
        data = j.read_bytes()
        res = {"mp3": run(elf, wrap_id3(data)), "flac": run(elf, wrap_flac(data))}
        poisoned = {"mp3": run(elf_p, wrap_id3(data)), "flac": run(elf_p, wrap_flac(data))}
        got[j.stem] = res["mp3"]
        check(res["mp3"]["hash"] == res["flac"]["hash"] and res["mp3"]["rc"] == res["flac"]["rc"],
              f"{j.stem}: ID3 and FLAC wrappers decode to the same stash")
        check(res == poisoned, f"{j.stem}: poisoned work buffers change nothing")
        if "progressive" in j.stem:
            check(res["mp3"]["rc"] == 0 and res["mp3"]["fail"] != 0, f"{j.stem}: refused with a failure code ({res['mp3']['fail']})")
        else:
            check(res["mp3"]["rc"] == 1 and res["mp3"]["fail"] == 0, f"{j.stem}: decodes")
        if not update:
            check(golden.get(j.stem) == res["mp3"], f"{j.stem}: equals the recorded golden result")
    if update:
        golden_path.write_text(json.dumps(got, indent=2, sort_keys=True) + "\n")
        print(f"golden written to {golden_path}")
    print("PASSED" if not fails else f"{fails} FAILED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
