/* GENERATED by tools/gen_diag_features.py from fw/diag_features.json -- do not edit. The register of Diagnostic-Build-only code: dx = diagnostics,
 * fx = features still incubating behind the flag. Every converted feature defaults to TAU_DIAGNOSTIC (the default Diagnostic Build is unchanged) and can be
 * overridden by the build: DIAG_DROP=<ids> (off) / FEATURES_ON=<ids> (an fx on in any build). See docs/features/DIAG_FEATURES.md. */
#ifndef TAU_DIAG_FEATURES_H
#define TAU_DIAG_FEATURES_H
#ifndef TAU_DIAGNOSTIC
#define TAU_DIAGNOSTIC 0
#endif

/* fx: Experimental meter parameters and presets (Layered Wave: anti-aliasing, layer blend, EQ-bell and CURVE spectrum styles, per-layer gains, the [EX] presets) */
#ifndef TAU_FX_METER_EXPERIMENTAL
#define TAU_FX_METER_EXPERIMENTAL TAU_DIAGNOSTIC
#endif

#endif
