/* GENERATED by tools/gen_meters.py -- do not edit by hand. Same order as the VIZ_*
 * enum; a retired slot's label is "-". */
static const char *const set_viz[] = { "BARS", "WATERFALL", "-", "PHASE SCOPE", "OSCILLOSCOPE", "VU", "WAVEFORM", "-", "PEAK DOTS", "-", "SPECTRUM", "-", "WINAMP BARS", "WINAMP SCOPE", "CHLADNI" };
_Static_assert(sizeof(set_viz) / sizeof(set_viz[0]) == VIZ_COUNT,
               "set_viz[] must name every visualizer");
