/* GENERATED by tools/gen_meters.py from meters/NAME/meter.json -- do not edit by hand (meter module M2, docs/METER_MODULE_SPEC.md).
 * Needs fw/meter_module.h and the VIZ_* enum (fw/meter_gen_enum.h) included first. */
#define MTR_MAX_PRE 8u

/* WINAMP BARS (id 12) */
enum { MP_WINAMP_BARS_BANDS, MP_WINAMP_BARS_EASE, MP_WINAMP_BARS_ATTACK, MP_WINAMP_BARS_RELEASE, MP_WINAMP_BARS_PEAK_ON, MP_WINAMP_BARS_PEAK_GRAVITY, MP_WINAMP_BARS_PEAK_HOLD_MS, MP_WINAMP_BARS_PEAK_FALL, MP_WINAMP_BARS_N };
static const char *const mtr_en_winamp_bars_ease[] = { "INSTANT", "LINEAR", "EXPONENTIAL", "SPRING" };
static const char *const mtr_en_winamp_bars_peak_gravity[] = { "LINEAR", "GRAVITY" };
static const mtr_param_t mtr_p_winamp_bars[MP_WINAMP_BARS_N] = {
    { "BANDS", MTR_U8, 4, 16, 1, 16, 255, 0, "", 0 },
    { "EASING", MTR_ENUM, 0, 3, 1, 2, 255, 0, "", mtr_en_winamp_bars_ease },
    { "ATTACK", MTR_U8, 1, 100, 5, 55, 255, 0, "", 0 },
    { "RELEASE", MTR_U8, 1, 100, 5, 22, 255, 0, "", 0 },
    { "PEAK CAP", MTR_BOOL, 0, 1, 1, 1, 255, 0, "", 0 },
    { "PEAK FALL STYLE", MTR_ENUM, 0, 1, 1, 1, 4, 1, "", mtr_en_winamp_bars_peak_gravity },
    { "PEAK HOLD", MTR_U16, 0, 800, 20, 200, 4, 1, " MS", 0 },
    { "PEAK FALL SPEED", MTR_U8, 1, 100, 5, 35, 4, 1, "", 0 },
};
static const char *mtr_pn_winamp_bars[MTR_MAX_PRE] = { "FLUID", "CLASSIC", "BOUNCY", "SLOW FADE", "SNAPPY" };
static char mtr_pb_winamp_bars[MTR_MAX_PRE][16];
static uint16_t mtr_pre_winamp_bars[MTR_MAX_PRE * MP_WINAMP_BARS_N] = {
    16, 2, 55, 22, 1, 1, 200, 35,   /* FLUID */
    16, 0, 100, 100, 1, 0, 0, 60,   /* CLASSIC */
    12, 3, 60, 25, 1, 1, 250, 30,   /* BOUNCY */
    8, 2, 30, 12, 1, 0, 500, 15,   /* SLOW FADE */
    16, 1, 90, 90, 1, 1, 100, 70,   /* SNAPPY */
};
static uint16_t mtr_v_winamp_bars[MP_WINAMP_BARS_N] = { 16, 2, 55, 22, 1, 1, 200, 35 };
static uint8_t mtr_pi_winamp_bars = 0;
static mtr_data_t mtr_d_winamp_bars = { VIZ_WINAMP_BARS, "WINAMP BARS", MP_WINAMP_BARS_N, mtr_p_winamp_bars, 5, MTR_MAX_PRE, mtr_pn_winamp_bars, mtr_pb_winamp_bars, mtr_pre_winamp_bars, mtr_v_winamp_bars, &mtr_pi_winamp_bars };
#define MV_WINAMP_BARS(name) (mtr_v_winamp_bars[MP_WINAMP_BARS_##name])

/* WINAMP SCOPE (id 13) */
enum { MP_WINAMP_SCOPE_SCOPE_SMOOTH, MP_WINAMP_SCOPE_SCOPE_TRAIL, MP_WINAMP_SCOPE_N };
static const mtr_param_t mtr_p_winamp_scope[MP_WINAMP_SCOPE_N] = {
    { "SCOPE SMOOTH", MTR_U8, 0, 90, 5, 35, 255, 0, "%", 0 },
    { "SCOPE TRAIL", MTR_U8, 0, 80, 5, 30, 255, 0, "%", 0 },
};
static const char *mtr_pn_winamp_scope[MTR_MAX_PRE] = { "FLUID", "CLASSIC", "BOUNCY", "SLOW FADE", "SNAPPY" };
static char mtr_pb_winamp_scope[MTR_MAX_PRE][16];
static uint16_t mtr_pre_winamp_scope[MTR_MAX_PRE * MP_WINAMP_SCOPE_N] = {
    35, 30,   /* FLUID */
    0, 0,   /* CLASSIC */
    45, 20,   /* BOUNCY */
    55, 40,   /* SLOW FADE */
    15, 5,   /* SNAPPY */
};
static uint16_t mtr_v_winamp_scope[MP_WINAMP_SCOPE_N] = { 35, 30 };
static uint8_t mtr_pi_winamp_scope = 0;
static mtr_data_t mtr_d_winamp_scope = { VIZ_WINAMP_SCOPE, "WINAMP SCOPE", MP_WINAMP_SCOPE_N, mtr_p_winamp_scope, 5, MTR_MAX_PRE, mtr_pn_winamp_scope, mtr_pb_winamp_scope, mtr_pre_winamp_scope, mtr_v_winamp_scope, &mtr_pi_winamp_scope };
#define MV_WINAMP_SCOPE(name) (mtr_v_winamp_scope[MP_WINAMP_SCOPE_##name])

/* CHLADNI (id 14) */
enum { MP_CHLADNI_LAYOUT, MP_CHLADNI_LINE_WIDTH, MP_CHLADNI_MODES, MP_CHLADNI_RISE, MP_CHLADNI_FALL, MP_CHLADNI_MORPH, MP_CHLADNI_MORPH_GAIN, MP_CHLADNI_TRIGGER, MP_CHLADNI_REFRACTORY, MP_CHLADNI_TONAL, MP_CHLADNI_PAINT, MP_CHLADNI_N };
static const char *const mtr_en_chladni_layout[] = { "LATTICE", "SHIMMER" };
static const char *const mtr_en_chladni_paint[] = { "LINE", "EMBER", "OCEAN" };
static const mtr_param_t mtr_p_chladni[MP_CHLADNI_N] = {
    { "LAYOUT", MTR_ENUM, 0, 1, 1, 0, 255, 0, "", mtr_en_chladni_layout },
    { "LINE WIDTH", MTR_U16, 200, 6000, 25, 1245, 255, 0, "", 0 },
    { "MODES", MTR_U8, 1, 4, 1, 3, 255, 0, "", 0 },
    { "RISE", MTR_U16, 50, 6000, 50, 668, 255, 0, "", 0 },
    { "FALL", MTR_U16, 50, 6000, 50, 401, 255, 0, "", 0 },
    { "MORPH SPEED", MTR_U16, 0, 1024, 8, 63, 255, 0, "", 0 },
    { "MORPH GAIN", MTR_U16, 0, 2048, 16, 391, 255, 0, "", 0 },
    { "TRIGGER GAIN", MTR_U8, 4, 100, 1, 26, 255, 0, "", 0 },
    { "REFRACTORY", MTR_U16, 50, 2000, 25, 600, 255, 0, " MS", 0 },
    { "TONAL TRIGGER", MTR_BOOL, 0, 1, 1, 0, 255, 0, "", 0 },
    { "PAINT", MTR_ENUM, 0, 2, 1, 0, 255, 0, "", mtr_en_chladni_paint },
};
static const char *mtr_pn_chladni[MTR_MAX_PRE] = { "LATTICE", "SHIMMER", "EMBER", "OCEAN" };
static char mtr_pb_chladni[MTR_MAX_PRE][16];
static uint16_t mtr_pre_chladni[MTR_MAX_PRE * MP_CHLADNI_N] = {
    0, 1245, 3, 668, 401, 63, 391, 26, 600, 0, 0,   /* LATTICE */
    1, 1475, 4, 1455, 873, 125, 782, 26, 350, 1, 0,   /* SHIMMER */
    0, 1245, 3, 668, 401, 63, 391, 26, 600, 0, 1,   /* EMBER */
    0, 1245, 3, 668, 401, 63, 391, 26, 600, 0, 2,   /* OCEAN */
};
static uint16_t mtr_v_chladni[MP_CHLADNI_N] = { 0, 1245, 3, 668, 401, 63, 391, 26, 600, 0, 0 };
static uint8_t mtr_pi_chladni = 0;
static mtr_data_t mtr_d_chladni = { VIZ_CHLADNI, "CHLADNI", MP_CHLADNI_N, mtr_p_chladni, 4, MTR_MAX_PRE, mtr_pn_chladni, mtr_pb_chladni, mtr_pre_chladni, mtr_v_chladni, &mtr_pi_chladni };
#define MV_CHLADNI(name) (mtr_v_chladni[MP_CHLADNI_##name])

/* MASTER VU (id 15) */
enum { MP_VU_MASTER_INFO, MP_VU_MASTER_COLOR_MODE, MP_VU_MASTER_COLOR_GREEN, MP_VU_MASTER_COLOR_YELLOW, MP_VU_MASTER_COLOR_RED, MP_VU_MASTER_N };
static const char *const mtr_en_vu_master_color_mode[] = { "THEME", "CUSTOM" };
static const mtr_param_t mtr_p_vu_master[MP_VU_MASTER_N] = {
    { "TECH INFO", MTR_BOOL, 0, 1, 1, 1, 255, 0, "", 0 },
    { "SEGMENT COLOUR", MTR_ENUM, 0, 1, 1, 0, 255, 0, "", mtr_en_vu_master_color_mode },
    { "GREEN", MTR_U16, 0, 65535, 1, 0, 1, 1, "", 0 },
    { "YELLOW", MTR_U16, 0, 65535, 1, 0, 1, 1, "", 0 },
    { "RED", MTR_U16, 0, 65535, 1, 0, 1, 1, "", 0 },
};
static const char *mtr_pn_vu_master[MTR_MAX_PRE] = { "THEME", "STANDARD", "CUSTOM EXAMPLE" };
static char mtr_pb_vu_master[MTR_MAX_PRE][16];
static uint16_t mtr_pre_vu_master[MTR_MAX_PRE * MP_VU_MASTER_N] = {
    1, 0, 0, 0, 0,   /* THEME */
    1, 1, 2016, 64992, 63488,   /* STANDARD */
    1, 1, 1622, 43835, 61775,   /* CUSTOM EXAMPLE */
};
static uint16_t mtr_v_vu_master[MP_VU_MASTER_N] = { 1, 0, 0, 0, 0 };
static uint8_t mtr_pi_vu_master = 0;
static mtr_data_t mtr_d_vu_master = { VIZ_VU_MASTER, "MASTER VU", MP_VU_MASTER_N, mtr_p_vu_master, 3, MTR_MAX_PRE, mtr_pn_vu_master, mtr_pb_vu_master, mtr_pre_vu_master, mtr_v_vu_master, &mtr_pi_vu_master };
#define MV_VU_MASTER(name) (mtr_v_vu_master[MP_VU_MASTER_##name])

#define MTR_MODULE_N 4u
static mtr_data_t *const mtr_modules[MTR_MODULE_N] = { &mtr_d_winamp_bars, &mtr_d_winamp_scope, &mtr_d_chladni, &mtr_d_vu_master };
