/* GENERATED by tools/gen_meters.py -- do not edit by hand. The list (Settings > Meter,
 * and the X button) is NOT in enum order: this is the owner's chosen order, sel_index
 * in each manifest. */
#define VIZ_SEL_COUNT 11u
static const uint8_t viz_order[VIZ_SEL_COUNT] = { VIZ_WINAMP_SCOPE, VIZ_WINAMP_BARS, VIZ_CHLADNI, VIZ_BARS, VIZ_WATER, VIZ_SCOPE, VIZ_WAVE, VIZ_VU, VIZ_SCROLL, VIZ_DOTS, VIZ_LED };
