/* GENERATED by tools/gen_meters.py from meters/NAME/meter.json -- do not edit by hand (meter module M2, docs/METER_MODULE_SPEC.md).
 * Needs fw/meter_module.h and the VIZ_* enum (fw/meter_gen_enum.h) included first. */

/* WINAMP BARS (id 12) */
enum { MP_WINAMP_BARS_BANDS, MP_WINAMP_BARS_EASE, MP_WINAMP_BARS_ATTACK, MP_WINAMP_BARS_RELEASE, MP_WINAMP_BARS_PEAK_ON, MP_WINAMP_BARS_PEAK_GRAVITY, MP_WINAMP_BARS_PEAK_HOLD_MS, MP_WINAMP_BARS_PEAK_FALL, MP_WINAMP_BARS_N };
static const char *const mtr_en_winamp_bars_ease[] = { "INSTANT", "LINEAR", "EXPONENTIAL", "SPRING" };
static const char *const mtr_en_winamp_bars_peak_gravity[] = { "LINEAR", "GRAVITY" };
static const mtr_param_t mtr_p_winamp_bars[MP_WINAMP_BARS_N] = {
    { "BANDS", MTR_U8, 4, 16, 1, 16, 255, 0, "", 0 },
    { "EASING", MTR_ENUM, 0, 3, 1, 2, 255, 0, "", mtr_en_winamp_bars_ease },
    { "ATTACK", MTR_U8, 1, 100, 5, 55, 255, 0, "", 0 },
    { "RELEASE", MTR_U8, 1, 100, 5, 22, 255, 0, "", 0 },
    { "PEAK CAP", MTR_BOOL, 0, 1, 1, 1, 255, 0, "", 0 },
    { "PEAK FALL STYLE", MTR_ENUM, 0, 1, 1, 1, 4, 1, "", mtr_en_winamp_bars_peak_gravity },
    { "PEAK HOLD", MTR_U16, 0, 800, 20, 200, 4, 1, " MS", 0 },
    { "PEAK FALL SPEED", MTR_U8, 1, 100, 5, 35, 4, 1, "", 0 },
};
static const char *const mtr_pn_winamp_bars[5] = { "FLUID", "CLASSIC", "BOUNCY", "SLOW FADE", "SNAPPY" };
static const uint16_t mtr_pre_winamp_bars[5 * MP_WINAMP_BARS_N] = {
    16, 2, 55, 22, 1, 1, 200, 35,   /* FLUID */
    16, 0, 100, 100, 1, 0, 0, 60,   /* CLASSIC */
    12, 3, 60, 25, 1, 1, 250, 30,   /* BOUNCY */
    8, 2, 30, 12, 1, 0, 500, 15,   /* SLOW FADE */
    16, 1, 90, 90, 1, 1, 100, 70,   /* SNAPPY */
};
static uint16_t mtr_v_winamp_bars[MP_WINAMP_BARS_N] = { 16, 2, 55, 22, 1, 1, 200, 35 };
static uint8_t mtr_pi_winamp_bars = 0;
static const mtr_data_t mtr_d_winamp_bars = { VIZ_WINAMP_BARS, "WINAMP BARS", MP_WINAMP_BARS_N, mtr_p_winamp_bars, 5, mtr_pn_winamp_bars, mtr_pre_winamp_bars, mtr_v_winamp_bars, &mtr_pi_winamp_bars };
#define MV_WINAMP_BARS(name) (mtr_v_winamp_bars[MP_WINAMP_BARS_##name])

/* WINAMP SCOPE (id 13) */
enum { MP_WINAMP_SCOPE_SCOPE_SMOOTH, MP_WINAMP_SCOPE_SCOPE_TRAIL, MP_WINAMP_SCOPE_N };
static const mtr_param_t mtr_p_winamp_scope[MP_WINAMP_SCOPE_N] = {
    { "SCOPE SMOOTH", MTR_U8, 0, 90, 5, 35, 255, 0, "%", 0 },
    { "SCOPE TRAIL", MTR_U8, 0, 80, 5, 30, 255, 0, "%", 0 },
};
static const char *const mtr_pn_winamp_scope[5] = { "FLUID", "CLASSIC", "BOUNCY", "SLOW FADE", "SNAPPY" };
static const uint16_t mtr_pre_winamp_scope[5 * MP_WINAMP_SCOPE_N] = {
    35, 30,   /* FLUID */
    0, 0,   /* CLASSIC */
    45, 20,   /* BOUNCY */
    55, 40,   /* SLOW FADE */
    15, 5,   /* SNAPPY */
};
static uint16_t mtr_v_winamp_scope[MP_WINAMP_SCOPE_N] = { 35, 30 };
static uint8_t mtr_pi_winamp_scope = 0;
static const mtr_data_t mtr_d_winamp_scope = { VIZ_WINAMP_SCOPE, "WINAMP SCOPE", MP_WINAMP_SCOPE_N, mtr_p_winamp_scope, 5, mtr_pn_winamp_scope, mtr_pre_winamp_scope, mtr_v_winamp_scope, &mtr_pi_winamp_scope };
#define MV_WINAMP_SCOPE(name) (mtr_v_winamp_scope[MP_WINAMP_SCOPE_##name])

#define MTR_MODULE_N 2u
static const mtr_data_t *const mtr_modules[MTR_MODULE_N] = { &mtr_d_winamp_bars, &mtr_d_winamp_scope };
