/* Meter module data model and the generic parameter logic (docs/METER_MODULE_SPEC.md sections 3-5, M2). Portable like meter_core.h: no
 * MMIO, no engine calls (tools/check_meter_deps.py). fw/meters_gen.h (generated by tools/gen_meters.py from meters/<key>/meter.json)
 * supplies one mtr_data_t per meter that has parameters; the Configure page, the QR export and Select+X preset cycling walk it, so a
 * new meter needs no UI code. The rules are the ones the hand-written Configure page had: numeric values step and clamp, enums and
 * booleans wrap, editing anything marks the meter CUSTOM (preset index 0xFF), a preset copies every value. */
#ifndef TAU_METER_MODULE_H
#define TAU_METER_MODULE_H
#include <stdint.h>

enum { MTR_U8 = 0, MTR_U16, MTR_BOOL, MTR_ENUM };
#define MTR_NO_WHEN 0xFFu
#define MTR_CUSTOM  0xFFu

typedef struct {
    const char *label;               /* device label, upper case */
    uint8_t     type;                /* MTR_U8 | MTR_U16 | MTR_BOOL | MTR_ENUM */
    uint16_t    min, max, step, def;
    uint8_t     when_idx;            /* parameter that must equal when_val for this one to show; MTR_NO_WHEN = always */
    uint16_t    when_val;
    const char *unit;                /* appended to the value ("%", " MS") */
    const char *const *enums;        /* MTR_ENUM: value names */
} mtr_param_t;

typedef struct {
    uint8_t             viz;         /* the VIZ_* id (persisted meter index) */
    const char         *name;
    uint8_t             n;           /* parameters */
    const mtr_param_t  *p;
    uint8_t             npre;
    const char *const  *pre_names;
    const uint16_t     *pre;         /* npre x n values, row major */
    uint16_t           *val;         /* the live values, one array per meter (state is per meter, B-234) */
    uint8_t            *pre_idx;     /* current preset, or MTR_CUSTOM */
} mtr_data_t;

static inline int mtr_visible(const mtr_data_t *d, uint32_t i)
{
    return d->p[i].when_idx == MTR_NO_WHEN || d->val[d->p[i].when_idx] == d->p[i].when_val;
}

/* One Left/Right step on parameter i (dir = -1 or +1). Marks the meter CUSTOM. Numeric: step and clamp. Boolean and enum: wrap. */
static inline void mtr_adjust(const mtr_data_t *d, uint32_t i, int32_t dir)
{
    const mtr_param_t *p = &d->p[i];
    int32_t v = (int32_t)d->val[i];
    if (p->type == MTR_BOOL) v = v ? 0 : 1;
    else if (p->type == MTR_ENUM) { v += dir; if (v < (int32_t)p->min) v = (int32_t)p->max; else if (v > (int32_t)p->max) v = (int32_t)p->min; }
    else { v += dir * (int32_t)p->step; if (v < (int32_t)p->min) v = (int32_t)p->min; else if (v > (int32_t)p->max) v = (int32_t)p->max; }
    d->val[i] = (uint16_t)v;
    *d->pre_idx = MTR_CUSTOM;
}

static inline void mtr_apply_preset(const mtr_data_t *d, uint32_t idx)
{
    for (uint32_t i = 0; i < d->n; i++) d->val[i] = d->pre[idx * d->n + i];
    *d->pre_idx = (uint8_t)idx;
}

/* Preset stepped by dir with wrap; CUSTOM counts as preset 0 for stepping (the behaviour of the page it replaces). */
static inline void mtr_preset_step(const mtr_data_t *d, int32_t dir)
{
    int32_t p = (*d->pre_idx < d->npre) ? (int32_t)*d->pre_idx : 0;
    p += dir;
    if (p < 0) p = (int32_t)d->npre - 1; else if (p >= (int32_t)d->npre) p = 0;
    mtr_apply_preset(d, (uint32_t)p);
}
#endif
