/* GENERATED by tools/gen_meters.py from meters/NAME/meter.json -- do not edit by hand.
 * Meter module M0 (docs/METER_MODULE_SPEC.md section 10). Regenerate after editing a
 * manifest: python3 tools/gen_meters.py
 *
 * viz_mode is persisted as an INDEX on real hardware, so a meter's enum position can
 * NEVER move once shipped -- only append. New meters get the next free index in a new
 * meters/NAME/meter.json; retired meters keep their slot (selectable: false, name: "-").
 */
enum { VIZ_BARS = 0, VIZ_WATER, VIZ_RETIRED_LEVELS, VIZ_SCOPE, VIZ_WAVE, VIZ_VU, VIZ_SCROLL, VIZ_RETIRED_MIRROR, VIZ_DOTS, VIZ_RETIRED_EYE, VIZ_LED, VIZ_RETIRED_TAPE, VIZ_WINAMP_BARS, VIZ_WINAMP_SCOPE, VIZ_CHLADNI, VIZ_COUNT };
