/* GENERATED by tools/gen_themes.py from themes/*.json. Do not edit; edit the json and regenerate. */
#ifndef TAU_THEME_DATA_H
#define TAU_THEME_DATA_H

#define TH_THEME_N 2u
#define TH_LIGHT_ACC_MAX_L 110u   /* Light polarity: accents brighter than this luma are scaled down (th_accent_of) */
typedef struct { const char *name; uint8_t bg_luma[2]; uint16_t role[2][TR_COUNT]; } th_theme_t;
static const th_theme_t th_themes[TH_THEME_N] = {
  { "TAU", { 45u, 205u }, {
    { [TR_BG_BOTTOM] = 0x0000u, [TR_SURFACE] = 0x2945u, [TR_SURFACE_TRACK] = 0x18E3u, [TR_TEXT_PRIMARY] = 0xFFFFu, [TR_TEXT_SECONDARY] = 0x94B2u, [TR_ON_ACCENT] = 0x0000u, [TR_OK] = 0x0600u, [TR_WARN] = 0xFE60u, [TR_DANGER] = 0xF9C0u, [TR_BASE] = 0x0862u, [TR_CHROME] = 0x10E5u, [TR_PILL] = 0x0320u, [TR_ERROR] = 0xF800u, [TR_FAINT] = 0x6B4Du, [TR_SPLASH_BG] = 0x0841u, [TR_SPLASH_BAR] = 0x27ECu, [TR_FS_RED] = 0xF249u, [TR_FS_TRACK] = 0x1905u },
    { [TR_BG_BOTTOM] = 0xEF9Du, [TR_SURFACE] = 0xFFFFu, [TR_SURFACE_TRACK] = 0xCE9Bu, [TR_TEXT_PRIMARY] = 0x10C4u, [TR_TEXT_SECONDARY] = 0x52ACu, [TR_ON_ACCENT] = 0xFFFFu, [TR_OK] = 0x13C6u, [TR_WARN] = 0xB340u, [TR_DANGER] = 0xC103u, [TR_BASE] = 0xE73Du, [TR_CHROME] = 0xDF1Cu, [TR_PILL] = 0xBF38u, [TR_ERROR] = 0xC103u, [TR_FAINT] = 0x632Eu, [TR_SPLASH_BG] = 0xEF9Du, [TR_SPLASH_BAR] = 0x14EDu, [TR_FS_RED] = 0xD1A7u, [TR_FS_TRACK] = 0xC67Au },
  } },
  { "OCEAN", { 40u, 210u }, {
    { [TR_BG_BOTTOM] = 0x0022u, [TR_SURFACE] = 0x1148u, [TR_SURFACE_TRACK] = 0x08C5u, [TR_TEXT_PRIMARY] = 0xE79Fu, [TR_TEXT_SECONDARY] = 0x8D79u, [TR_ON_ACCENT] = 0x0084u, [TR_OK] = 0x262Bu, [TR_WARN] = 0xF580u, [TR_DANGER] = 0xEA28u, [TR_BASE] = 0x08A4u, [TR_CHROME] = 0x1107u, [TR_PILL] = 0x0A4Bu, [TR_ERROR] = 0xFB4Du, [TR_FAINT] = 0x6C54u, [TR_SPLASH_BG] = 0x0084u, [TR_SPLASH_BAR] = 0x2E97u, [TR_FS_RED] = 0xF38Eu, [TR_FS_TRACK] = 0x1989u },
    { [TR_BG_BOTTOM] = 0xE79Eu, [TR_SURFACE] = 0xFFFFu, [TR_SURFACE_TRACK] = 0xC6DCu, [TR_TEXT_PRIMARY] = 0x0928u, [TR_TEXT_SECONDARY] = 0x430Fu, [TR_ON_ACCENT] = 0xFFFFu, [TR_OK] = 0x13C8u, [TR_WARN] = 0xA300u, [TR_DANGER] = 0xB925u, [TR_BASE] = 0xDF5Eu, [TR_CHROME] = 0xCEFDu, [TR_PILL] = 0xB71Du, [TR_ERROR] = 0xB925u, [TR_FAINT] = 0x53B2u, [TR_SPLASH_BG] = 0xE79Eu, [TR_SPLASH_BAR] = 0x1473u, [TR_FS_RED] = 0xD1E7u, [TR_FS_TRACK] = 0xBE7Cu },
  } },
};

#endif
