#!/usr/bin/env python3
"""Generate fw/meter_gen.h from meters/*/meter.json (Meter module M0, docs/METER_MODULE_SPEC.md).

Scope of M0, deliberately narrow: this replaces only the hand-maintained VIZ_* enum, the
set_viz[] name table and the viz_order[]/selectable-order remap in fw/player.c and
fw/settingsui.inc. It does NOT touch: the dispatch chain (the per-meter drawing code stays
exactly where it is), meter_afford()'s hardware-spectrum gate list, the X-cycle toast strings,
or fw/meter_thumbs.h (which documents itself as hand-authored source of truth, not
regeneratable -- see tools/gen_meter_thumbs.py's own note).

Each meters/<key>/meter.json carries:
    key         directory/manifest name, lower_snake
    enum        the VIZ_* C identifier
    index       its FIXED enum position (viz_mode persists as this index on real hardware;
                never reorder these once shipped)
    name        the settings-list / set_viz[] label ("-" for a retired, code-free slot)
    selectable  true if it appears in the Settings > Meter list and the X-cycle
    sel_index   position in viz_order[] (only when selectable)
    retired     true for a slot kept only so old saved indices keep resolving (optional)
    needs_hw_spec  true if this meter is gated in meter_afford()'s caller list (informational
                   only in M0 -- the gate list itself is not generated yet)

Usage: python3 tools/gen_meters.py [--dir meters] [--out fw/meter_gen.h] [--check]
--check regenerates into a temp file and diffs against --out (used by make test-host);
exits non-zero and prints a diff-like message if they differ.
"""
import argparse
import glob
import json
import os
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_meters(meters_dir):
    paths = sorted(glob.glob(os.path.join(meters_dir, "*", "meter.json")))
    if not paths:
        raise SystemExit(f"no meter.json files found under {meters_dir}")
    meters = []
    for p in paths:
        with open(p) as f:
            m = json.load(f)
        for req in ("key", "enum", "index", "name", "selectable"):
            if req not in m:
                raise SystemExit(f"{p}: missing required field {req!r}")
        m["_path"] = p
        meters.append(m)
    return meters


def load_planned(meters_dir):
    """meters/planned/*/meter.json: manifests that exist for Tau Omega and the preview lab before any firmware module does. They reach
    tools/meters_schema.json and the docs (planned: true) but NEVER the generated firmware files, so a planned meter cannot grow the ROM or RAM."""
    out = []
    for p in sorted(glob.glob(os.path.join(meters_dir, "planned", "*", "meter.json"))):
        with open(p) as f:
            m = json.load(f)
        for req in ("key", "enum", "index", "name", "selectable"):
            if req not in m:
                raise SystemExit(f"{p}: missing required field {req!r}")
        if m["selectable"]:
            raise SystemExit(f"{p}: a planned meter cannot be selectable")
        m["_path"], m["planned"] = p, True
        out.append(m)
    return out


def validate(meters):
    by_index = sorted(meters, key=lambda m: m["index"])
    indices = [m["index"] for m in by_index]
    if indices != list(range(len(indices))):
        raise SystemExit(f"meter 'index' fields must be exactly 0..{len(indices)-1} with no gaps or "
                          f"duplicates; got {indices}")
    enums = [m["enum"] for m in by_index]
    if len(set(enums)) != len(enums):
        raise SystemExit(f"duplicate enum names: {enums}")

    selectable = [m for m in by_index if m["selectable"]]
    sel_indices = sorted(m["sel_index"] for m in selectable)
    if sel_indices != list(range(len(selectable))):
        raise SystemExit(f"selectable meters' 'sel_index' fields must be exactly "
                          f"0..{len(selectable)-1} with no gaps or duplicates; got {sel_indices}")
    for m in by_index:
        if not m["selectable"] and "sel_index" in m:
            raise SystemExit(f"{m['_path']}: sel_index set on a non-selectable meter")
    return by_index, sorted(selectable, key=lambda m: m["sel_index"])


def render_enum(by_index):
    """The VIZ_* enum. Included where the hand-written enum used to sit, BEFORE anything that
    names a VIZ_* constant (thumb_slot(), the dispatch chain, ...)."""
    lines = []
    lines.append("/* GENERATED by tools/gen_meters.py from meters/NAME/meter.json -- do not edit by hand.")
    lines.append(" * Meter module M0 (docs/METER_MODULE_SPEC.md section 10). Regenerate after editing a")
    lines.append(" * manifest: python3 tools/gen_meters.py")
    lines.append(" *")
    lines.append(" * viz_mode is persisted as an INDEX on real hardware, so a meter's enum position can")
    lines.append(" * NEVER move once shipped -- only append. New meters get the next free index in a new")
    lines.append(" * meters/NAME/meter.json; retired meters keep their slot (selectable: false, name: \"-\").")
    lines.append(" */")
    enum_names = [m["enum"] for m in by_index]
    lines.append("enum { " + f"{enum_names[0]} = 0, " + ", ".join(enum_names[1:]) + ", VIZ_COUNT };")
    lines.append("")
    return "\n".join(lines)


def render_names(by_index):
    """set_viz[]. Included exactly where the hand-written array used to sit (fw/settingsui.inc,
    between the stress/soak choice tables and set_rep[])."""
    lines = []
    lines.append("/* GENERATED by tools/gen_meters.py -- do not edit by hand. Same order as the VIZ_*")
    lines.append(" * enum; a retired slot's label is \"-\". */")
    name_list = ", ".join(json.dumps(m["name"]) for m in by_index)
    lines.append("static const char *const set_viz[] = { " + name_list + " };")
    lines.append("_Static_assert(sizeof(set_viz) / sizeof(set_viz[0]) == VIZ_COUNT,")
    lines.append('               "set_viz[] must name every visualizer");')
    lines.append("")
    return "\n".join(lines)


def render_order(by_sel):
    """VIZ_SEL_COUNT / viz_order[]. Included where the hand-written pair used to sit in
    fw/player.c (after thumb_slot(), before bars_layout/viz_sel_to_mode)."""
    lines = []
    lines.append("/* GENERATED by tools/gen_meters.py -- do not edit by hand. The list (Settings > Meter,")
    lines.append(" * and the X button) is NOT in enum order: this is the owner's chosen order, sel_index")
    lines.append(" * in each manifest. */")
    lines.append(f"#define VIZ_SEL_COUNT {len(by_sel)}u")
    sel_names = ", ".join(m["enum"] for m in by_sel)
    lines.append(f"static const uint8_t viz_order[VIZ_SEL_COUNT] = {{ {sel_names} }};")
    lines.append("")
    return "\n".join(lines)



def cid(s):
    return "".join(ch if ch.isalnum() else "_" for ch in s).upper()


def render_modules(meters):
    """fw/meters_gen.h (M2): for every meter with parameters, the parameter table, presets, live values and a mtr_data_t (fw/meter_module.h).
    The firmware, the Configure page, the QR export and Select+X preset cycling all read this; nothing about a meter's parameters is
    written by hand in C any more."""
    mods = [m for m in sorted(meters, key=lambda m: m["index"]) if m.get("params")]
    tmap = {"u8": "MTR_U8", "u16": "MTR_U16", "bool": "MTR_BOOL", "enum": "MTR_ENUM"}
    o = ["/* GENERATED by tools/gen_meters.py from meters/NAME/meter.json -- do not edit by hand (meter module M2, docs/METER_MODULE_SPEC.md).",
         " * Needs fw/meter_module.h and the VIZ_* enum (fw/meter_gen_enum.h) included first. */", "#define MTR_MAX_PRE 8u", ""]
    for m in mods:
        k, K = m["key"], cid(m["key"])
        ps = m["params"]
        idx = {x["key"]: i for i, x in enumerate(ps)}
        if len(ps) > 12:
            raise SystemExit(f"{m['_path']}: at most 12 parameters (MTR_MAX_PARAMS)")
        if len(m["presets"]) > 8:
            raise SystemExit(f"{m['_path']}: at most 8 presets (MTR_MAX_PRE)")
        o.append("/* %s (id %d) */" % (m["name"], m["index"]))
        o.append("enum { " + ", ".join("MP_%s_%s" % (K, cid(x["key"])) for x in ps) + ", MP_%s_N };" % K)
        for x in ps:
            if x["type"] == "enum":
                o.append("static const char *const mtr_en_%s_%s[] = { %s };" % (k, x["key"], ", ".join(json.dumps(v) for v in x["values"])))
        o.append("static const mtr_param_t mtr_p_%s[MP_%s_N] = {" % (k, K))
        for x in ps:
            lo, hi = param_bounds(x)
            w = x.get("when", {})
            wi, wv = (idx[next(iter(w))], w[next(iter(w))]) if w else (255, 0)
            unit = x.get("unit", "")
            unit = unit if unit == "%" else ((" " + unit.upper()) if unit else "")
            o.append("    { %s, %s, %d, %d, %d, %d, %d, %d, %s, %s }," % (
                json.dumps(x["label"].upper()), tmap[x["type"]], lo, hi, x.get("step", 1), x["default"], wi, wv, json.dumps(unit),
                ("mtr_en_%s_%s" % (k, x["key"])) if x["type"] == "enum" else "0"))
        o.append("};")
        npre = len(m["presets"])
        o.append("static const char *mtr_pn_%s[MTR_MAX_PRE] = { %s };" % (k, ", ".join(json.dumps(pr["name"]) for pr in m["presets"])))
        o.append("static char mtr_pb_%s[MTR_MAX_PRE][16];" % k)
        o.append("static uint16_t mtr_pre_%s[MTR_MAX_PRE * MP_%s_N] = {" % (k, K))
        for pr in m["presets"]:
            o.append("    " + ", ".join(str(pr["values"][x["key"]]) for x in ps) + ",   /* " + pr["name"] + " */")
        o.append("};")
        dp = m["presets"][m["default_preset"]]["values"]
        o.append("static uint16_t mtr_v_%s[MP_%s_N] = { %s };" % (k, K, ", ".join(str(dp[x["key"]]) for x in ps)))
        o.append("static uint8_t mtr_pi_%s = %d;" % (k, m["default_preset"]))
        o.append("static mtr_data_t mtr_d_%s = { %s, %s, MP_%s_N, mtr_p_%s, %d, MTR_MAX_PRE, mtr_pn_%s, mtr_pb_%s, mtr_pre_%s, mtr_v_%s, &mtr_pi_%s };" % (
            k, m["enum"], json.dumps(m["name"]), K, k, npre, k, k, k, k, k))
        o.append("#define MV_%s(name) (mtr_v_%s[MP_%s_##name])" % (K, k, K))
        o.append("")
    o.append("#define MTR_MODULE_N %du" % len(mods))
    o.append("static mtr_data_t *const mtr_modules[MTR_MODULE_N] = { " + ", ".join("&mtr_d_%s" % m["key"] for m in mods) + " };")
    o.append("")
    return "\n".join(o)


CAPS_PATH = os.path.join(ROOT, "tools", "meter_capabilities.json")
CAPS_DOC = os.path.join(ROOT, "docs", "METER_CAPABILITIES.md")
BLOCKED_FOR_SELECTABLE = ("shelved", "design-only", "sim-only", "fit-timing-open")   # M0.5: evidence gates the build


def load_caps():
    with open(CAPS_PATH) as f:
        c = json.load(f)
    keys = [x["key"] for x in c["capabilities"]]
    if len(set(keys)) != len(keys):
        raise SystemExit("duplicate capability keys in meter_capabilities.json")
    for x in c["capabilities"]:
        for req in ("key", "provider", "status", "ready_probe", "cost", "cost_basis", "fallback"):
            if req not in x:
                raise SystemExit(f"capability {x.get('key')}: missing {req!r}")
        if x["status"] not in c["statuses"]:
            raise SystemExit(f"capability {x['key']}: unknown status {x['status']!r}")
        if x["cost_basis"] not in ("measured", "model"):
            raise SystemExit(f"capability {x['key']}: cost_basis must be measured or model")
    return c


def validate_caps(meters, caps):
    """M0.5: a manifest may only list capabilities that exist, and a selectable meter may only use ones with hardware evidence.
    needs_hw_spec and the hw_spectrum capability must agree (they describe the same gate)."""
    by_key = {x["key"]: x for x in caps["capabilities"]}
    for m in meters:
        used = m.get("caps", [])
        for k in used:
            if k not in by_key:
                raise SystemExit(f"{m['_path']}: unknown capability {k!r} (not in tools/meter_capabilities.json)")
            if m["selectable"] and by_key[k]["status"] in BLOCKED_FOR_SELECTABLE:
                raise SystemExit(f"{m['_path']}: selectable meter uses {k!r}, status {by_key[k]['status']!r}; only hardware-proven "
                                 f"capabilities may back a selectable meter (docs/METER_MODULE_SPEC.md section 12)")
        if bool(m.get("needs_hw_spec")) != ("hw_spectrum" in used):
            raise SystemExit(f"{m['_path']}: needs_hw_spec and the hw_spectrum capability disagree")
        if m.get("cost_class") is not None and m["cost_class"] not in (0, 1, 2):
            raise SystemExit(f"{m['_path']}: cost_class must be 0, 1 or 2")


def render_caps_doc(caps, meters):
    used_by = {}
    for m in meters:
        for k in m.get("caps", []):
            used_by.setdefault(k, []).append(m["key"])
    out = ["# Meter capabilities (generated)", "",
           "GENERATED by `tools/gen_meters.py` from `tools/meter_capabilities.json` and `meters/*/meter.json`. Do not edit; change the JSON.",
           "Rules (docs/METER_MODULE_SPEC.md section 12): a manifest may list only capabilities in this registry, and a selectable meter may",
           "only use `hardware-proven` ones. `cost_basis` says whether the cost is measured on a Pocket or a model estimate.", "",
           "| Capability | Status | Provider | Probe | Cost | Basis | Fallback | Used by |", "|---|---|---|---|---|---|---|---|"]
    for x in caps["capabilities"]:
        out.append("| `%s` | %s | %s | %s | %s | %s | %s | %s |" % (
            x["key"], x["status"], x["provider"], x["ready_probe"], x["cost"], x["cost_basis"], x["fallback"],
            ", ".join(used_by.get(x["key"], [])) or "none"))
    out += ["", "## Notes", ""] + ["- **%s**: %s" % (x["key"], x["note"]) for x in caps["capabilities"] if x.get("note")]
    out += ["", "## Meters", "", "| Meter | Cost class | Capabilities | Considered |", "|---|---|---|---|"]
    for m in sorted(meters, key=lambda m: m["index"]):
        if m.get("retired"):
            continue
        out.append("| %s | %s | %s | %s |" % (m["key"], m.get("cost_class", "-"), ", ".join(m.get("caps", [])) or "none (base rect)", m.get("considered", "")))
    unused = [x["key"] for x in caps["capabilities"] if x["key"] not in used_by]
    out += ["", "Capabilities no meter uses: " + (", ".join(unused) or "none") + ".", ""]
    return "\n".join(out)


SCHEMA_PATH = os.path.join(ROOT, "tools", "meters_schema.json")
REGISTRY_DOC = os.path.join(ROOT, "docs", "METER_REGISTRY.md")
PARAM_TYPES = ("u8", "u16", "bool", "enum")


def param_bounds(p):
    if p["type"] == "bool":
        return 0, 1
    if p["type"] == "enum":
        return 0, len(p["values"]) - 1
    return p["min"], p["max"]


def validate_params(m):
    """M1: parameters use only u8/u16/bool/enum (generic UI, wire format and file format), defaults and presets stay in range, `when`
    names an existing parameter, presets are complete."""
    params = m.get("params", [])
    keys = [x["key"] for x in params]
    where = m["_path"]
    if len(set(keys)) != len(keys):
        raise SystemExit(f"{where}: duplicate parameter keys")
    for x in params:
        for req in ("key", "label", "type", "default"):
            if req not in x:
                raise SystemExit(f"{where}: parameter {x.get('key')!r} missing {req!r}")
        if x["type"] not in PARAM_TYPES:
            raise SystemExit(f"{where}: parameter {x['key']}: type must be one of {PARAM_TYPES}")
        if x["type"] in ("u8", "u16"):
            if not all(k in x for k in ("min", "max", "step")):
                raise SystemExit(f"{where}: parameter {x['key']}: u8/u16 need min, max and step")
            cap = 255 if x["type"] == "u8" else 65535
            if not (0 <= x["min"] <= x["max"] <= cap) or x["step"] < 1:
                raise SystemExit(f"{where}: parameter {x['key']}: bad range or step")
        if x["type"] == "enum" and not (2 <= len(x.get("values", [])) <= 16):
            raise SystemExit(f"{where}: parameter {x['key']}: enum needs 2..16 values")
        lo, hi = param_bounds(x)
        if not lo <= x["default"] <= hi:
            raise SystemExit(f"{where}: parameter {x['key']}: default {x['default']} outside {lo}..{hi}")
        for k in x.get("when", {}):
            if k not in keys or k == x["key"]:
                raise SystemExit(f"{where}: parameter {x['key']}: 'when' names {k!r}, not another parameter of this meter")
    presets = m.get("presets", [])
    if presets and not params:
        raise SystemExit(f"{where}: presets without parameters")
    if params and not presets:
        raise SystemExit(f"{where}: a meter with parameters needs at least one preset (the default)")
    names = [pr["name"] for pr in presets]
    if len(set(names)) != len(names) or any(not (1 <= len(n) <= 15) for n in names):
        raise SystemExit(f"{where}: preset names must be unique, 1..15 characters")
    by_key = {x["key"]: x for x in params}
    for pr in presets:
        if set(pr["values"]) != set(keys):
            raise SystemExit(f"{where}: preset {pr['name']} must give exactly the parameters {keys}")
        for k, v in pr["values"].items():
            lo, hi = param_bounds(by_key[k])
            if not lo <= v <= hi:
                raise SystemExit(f"{where}: preset {pr['name']}: {k}={v} outside {lo}..{hi}")
    if presets and not 0 <= m.get("default_preset", -1) < len(presets):
        raise SystemExit(f"{where}: default_preset must index a preset")
    # the declared defaults must equal the default preset (one source of truth for the boot values)
    if presets:
        dp = presets[m["default_preset"]]["values"]
        for x in params:
            if x["default"] != dp[x["key"]]:
                raise SystemExit(f"{where}: parameter {x['key']} default {x['default']} differs from the default preset ({dp[x['key']]})")


def render_schema(meters):
    """tools/meters_schema.json: the whole registry, the one file Tau Omega and the preview stack read."""
    out = {"registry_version": 1, "meters": []}
    for m in sorted(meters, key=lambda m: m["index"]):
        e = {"id": m["index"], "schema": m.get("schema", 1), "key": m["key"], "name": m["name"], "enum": m["enum"], "selectable": bool(m["selectable"]),
             "retired": bool(m.get("retired")), "cost_class": m.get("cost_class"), "caps": m.get("caps", []),
             "needs_hw_spec": bool(m.get("needs_hw_spec")), "params": m.get("params", []), "presets": m.get("presets", []),
             "default_preset": m.get("default_preset")}
        if m.get("planned"):
            e["planned"] = True
        if m["selectable"]:
            e["list_position"] = m["sel_index"]
        out["meters"].append(e)
    return json.dumps(out, indent=1) + "\n"


def render_registry_doc(meters):
    lines = ["# Meter registry (generated)", "",
             "GENERATED by `tools/gen_meters.py` from `meters/*/meter.json`. Do not edit; change the manifest. The machine-readable form is",
             "`tools/meters_schema.json`. Ids are append-only (`viz_mode` persists as the id).", "",
             "| Id | Key | Name | List position | Selectable | Cost class | Parameters | Presets |", "|---|---|---|---|---|---|---|---|"]
    for m in sorted(meters, key=lambda m: m["index"]):
        lines.append("| %d | %s | %s | %s | %s | %s | %s | %s |" % (
            m["index"], m["key"], m["name"], m.get("sel_index", "-"), "yes" if m["selectable"] else ("retired" if m.get("retired") else ("planned" if m.get("planned") else "parked")),
            m.get("cost_class", "-"), ", ".join(x["key"] for x in m.get("params", [])) or "-",
            ", ".join(pr["name"] for pr in m.get("presets", [])) or "-"))
    for m in sorted(meters, key=lambda m: m["index"]):
        if not m.get("params"):
            continue
        lines += ["", "## %s (id %d)" % (m["name"], m["index"]), "", "| Parameter | Label | Type | Range | Step | Default | When |", "|---|---|---|---|---|---|---|"]
        for x in m["params"]:
            rng = "%s" % x["values"] if x["type"] == "enum" else ("0/1" if x["type"] == "bool" else "%s..%s" % (x["min"], x["max"]))
            lines.append("| %s | %s | %s | %s | %s | %s | %s |" % (x["key"], x["label"], x["type"], rng, x.get("step", 1), x["default"],
                                                                 ", ".join("%s=%s" % kv for kv in x.get("when", {}).items()) or "-"))
    return "\n".join(lines) + "\n"


OUTPUTS = {
    "enum": ("meter_gen_enum.h", render_enum, lambda by_index, by_sel: render_enum(by_index)),
    "names": ("meter_gen_names.h", render_names, lambda by_index, by_sel: render_names(by_index)),
    "order": ("meter_gen_order.h", render_order, lambda by_index, by_sel: render_order(by_sel)),
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default=os.path.join(ROOT, "meters"))
    ap.add_argument("--fw-dir", default=os.path.join(ROOT, "fw"))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    meters = load_meters(args.dir)
    by_index, by_sel = validate(meters)
    planned = load_planned(args.dir)
    taken = {m["index"] for m in meters}
    for m in planned:
        if m["index"] in taken or m["index"] < len(meters):
            raise SystemExit(f"{m['_path']}: planned index {m['index']} collides with a firmware meter (firmware ids are 0..{len(meters)-1})")
        taken.add(m["index"])
    if len({m["enum"] for m in meters + planned}) != len(meters + planned):
        raise SystemExit("a planned meter reuses an enum name")
    caps = load_caps()
    validate_caps(meters + planned, caps)
    for m in meters + planned:
        validate_params(m)

    ok = True
    for _key, (fname, _renderfn, gen) in OUTPUTS.items():
        text = gen(by_index, by_sel)
        out = os.path.join(args.fw_dir, fname)
        if args.check:
            if not os.path.exists(out):
                print(f"{out} does not exist; run without --check first", file=sys.stderr)
                ok = False
                continue
            with open(out) as f:
                current = f.read()
            if current != text:
                print(f"{out} is stale relative to meters/NAME/meter.json; regenerate with "
                      f"'python3 tools/gen_meters.py'", file=sys.stderr)
                ok = False
            continue
        with open(out, "w") as f:
            f.write(text)
        print(f"wrote {out}")

    doc = render_caps_doc(caps, meters + planned)
    extra = [(os.path.join(ROOT, "fw", "meters_gen.h"), render_modules(meters)), (SCHEMA_PATH, render_schema(meters + planned)), (REGISTRY_DOC, render_registry_doc(meters + planned))]
    if args.check:
        for path, text in extra:
            if not os.path.exists(path) or open(path).read() != text:
                print(f"{path} is stale; regenerate with 'python3 tools/gen_meters.py'", file=sys.stderr)
                ok = False
    else:
        for path, text in extra:
            with open(path, "w") as f:
                f.write(text)
            print(f"wrote {path}")
    if args.check:
        if not os.path.exists(CAPS_DOC) or open(CAPS_DOC).read() != doc:
            print(f"{CAPS_DOC} is stale; regenerate with 'python3 tools/gen_meters.py'", file=sys.stderr)
            ok = False
    else:
        with open(CAPS_DOC, "w") as f:
            f.write(doc)
        print(f"wrote {CAPS_DOC}")
    if args.check:
        return 0 if ok else 1
    print(f"({len(by_index)} meters, {len(by_sel)} selectable)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
