#!/usr/bin/env python3
"""Generate the coefficient ROM for the hardware Cymo resampler (src/fpga/core/tau_cymo_resamp.sv,
docs/features/CYMO_AUDIO_ENGINE.md section 15/9, docs/AUDIT_TRAIL.md B-467+).

Reuses tools/lab/cymo_resamp_model.py's own prototype-filter design (P=160, Q=147 exact 44100->48000
ratio, Kaiser window beta=8.6, the combination that doc's own sweep table found gives 32 taps / 83-86 dB
SINAD across the audible band) so the RTL ROM and the lab tool's own SINAD predictions are built from the
IDENTICAL filter design -- only the final quantization step differs (see below), and that difference is
recorded here rather than silently diverging from the doc.

QUANTIZATION DIFFERENCE FROM THE LAB MODEL (deliberate, not a bug): cymo_resamp_model.py quantizes to
scale = 2**15 - 1 = 32767 for its own float-domain SINAD prediction math, which has no particular hardware
meaning. This generator quantizes to a clean power-of-two scale = 2**15 = 32768 (standard Q1.15 fixed
point) instead, so the RTL's own output stage is a single arithmetic right-shift (>>> 15) with no
remainder handling -- the standard, cheap hardware convention. The SINAD difference between the two
scales is below the resolution of a 16-bit coefficient (1 part in 32768) and does not change any
conclusion in the sweep table.

Each of the P=160 banks is independently normalised to unity DC gain post-quantization (same as
build_banks()), then rounded to a signed 16-bit Q1.15 integer. Output: one flat ROM, address =
bank*TAPS + tap (bank 0..159, tap 0..31, tap 0 pairs with the MOST RECENT history sample -- the module's
own hist[0]-is-newest convention, matching tau_flac_lpc.sv's register contract note).

Outputs:
  --sv PATH   a SystemVerilog `include with a `coef_rom` memory array + initial-block ROM load
              (an M10K-sized flat ROM, not a case-statement function -- see the file's own comment
              for why: a 5,120-entry case function is needlessly slow to compile/simulate at this scale,
              an initial-block array load is the standard inferable-ROM idiom at this size).
  --h PATH    a C header (`cymo_coef_rom[5120]`) for the golden model (sim/cymo_resamp_model.c).

Usage:
    python3 tools/gen_cymo_resamp_rom.py --sv src/fpga/core/tau_cymo_resamp_rom.svh --h sim/cymo_resamp_rom.h
"""
import argparse
import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LAB = ROOT / "tools/lab/cymo_resamp_model.py"

TAPS = 32
SCALE = 1 << 15   # Q1.15, power-of-two (see module docstring above for why this differs from the lab tool's 32767)


def _load_lab_model():
    spec = importlib.util.spec_from_file_location("cymo_resamp_model", LAB)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def build_rom(crm):
    """Mirrors crm.build_banks(TAPS, "kaiser") exactly, except the final quantized INTEGER values are
    kept (not divided back to float) -- these integers are exactly what the ROM stores."""
    h = crm.design_prototype(TAPS, "kaiser")
    P = crm.P
    banks_f = [[0.0] * TAPS for _ in range(P)]
    for i, v in enumerate(h):
        bank, tap = i % P, i // P
        if tap < TAPS:
            banks_f[bank][tap] = v
    rom = []
    for bank in banks_f:
        dc = sum(bank)
        norm = [c / dc if dc != 0 else c for c in bank] if dc != 0 else bank
        q = [max(-SCALE, min(SCALE - 1, round(c * SCALE))) for c in norm]
        rom.extend(q)
    assert len(rom) == P * TAPS
    return rom, P


def render_sv(rom, P):
    o = [
        "// GENERATED by tools/gen_cymo_resamp_rom.py from a Kaiser-windowed (beta=8.6) polyphase prototype,",
        "// the same design tools/lab/cymo_resamp_model.py uses for its own SINAD predictions (160 banks, 32",
        "// taps/bank, exact 44100->48000 ratio). Do not edit by hand: sim/test_cymo_resamp_rom.py fails if",
        "// this file differs from a fresh generation.",
        "//",
        f"// address = bank*{TAPS} + tap  (bank 0..{P-1}, tap 0..{TAPS-1}; tap 0 pairs with the newest history sample).",
        "// Q1.15 signed fixed point (scale 32768): output = (sum(coef[t]*hist[t])) >>> 15.",
        "",
        f"localparam integer CYMO_RESAMP_TAPS   = {TAPS};",
        f"localparam integer CYMO_RESAMP_BANKS  = {P};",
        f"(* ramstyle = \"M10K\" *) reg signed [15:0] coef_rom [0:{P*TAPS-1}];",
        "initial begin",
    ]
    for i, v in enumerate(rom):
        if v >= 0:
            o.append(f"    coef_rom[{i}] = 16'sd{v};")
        else:
            o.append(f"    coef_rom[{i}] = -16'sd{-v};")
    o.append("end")
    o.append("")
    return "\n".join(o)


def render_h(rom, P):
    o = [
        "/* GENERATED by tools/gen_cymo_resamp_rom.py -- do not edit. */",
        f"#define CYMO_RESAMP_TAPS {TAPS}",
        f"#define CYMO_RESAMP_BANKS {P}",
        "static const short cymo_coef_rom[%d] = {" % (P * TAPS),
        ",".join(str(v) for v in rom),
        "};",
    ]
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--sv", type=Path)
    ap.add_argument("--h", type=Path)
    a = ap.parse_args()
    crm = _load_lab_model()
    rom, P = build_rom(crm)
    if a.sv:
        a.sv.write_text(render_sv(rom, P))
    if a.h:
        a.h.write_text(render_h(rom, P))
    if not a.sv and not a.h:
        print(f"generated {len(rom)} coefficients ({P} banks x {TAPS} taps), range "
              f"[{min(rom)}, {max(rom)}] (scale {SCALE})")
