#!/usr/bin/env python3
"""Generate fw/qr_tables.h (QR versions 1-38, error level L, byte mode) from the segno reference so the tables cannot be mistyped.
Run with the QR virtualenv: work/venv-qr/bin/python tools/gen_qr_tables.py"""
import segno.consts as c
from pathlib import Path

MAXV = 38
rows, align = [], []
cwmax = 0
for v in range(1, MAXV + 1):
    groups = c.ECC[v][c.ERROR_LEVEL_L]
    g = [(e.num_blocks, e.num_total, e.num_data) for e in groups]
    while len(g) < 2:
        g.append((0, 0, 0))
    rows.append(sum(g, ()))
    cwmax = max(cwmax, sum(n * (t + d) for n, t, d in g))
    pos = c.ALIGNMENT_POS[v - 2] if v >= 2 else ()
    align.append(list(pos) + [0] * (7 - len(pos)))
out = ["/* Generated by tools/gen_qr_tables.py from segno: QR versions 1-38, error level L. Do not edit. */",
       "#ifndef TAU_QR_TABLES_H", "#define TAU_QR_TABLES_H", "#include <stdint.h>", "",
       "#define QR_MAXV_T %du" % MAXV, "/* largest (data + total) codeword count over the versions: the size of the codeword scratch */", "#define QR_CW_MAX %du" % cwmax, "#define QR_ECL_BITS 1u   /* level L in the format information */", "",
       "/* per version (index v): blocks in group 1, codewords per block, data codewords per block, then group 2 (blocks may be 0) */",
       "QR_TBL static const uint16_t qr_ecc[%d][6] = {" % (MAXV + 1), "    {0, 0, 0, 0, 0, 0},"]
for r in rows:
    out.append("    {%s}," % ", ".join(str(x) for x in r))
out += ["};", "", "/* alignment pattern centre coordinates per version (0 = unused) */", "QR_TBL static const uint8_t qr_align[%d][7] = {" % (MAXV + 1), "    {0,0,0,0,0,0,0},"]
for a in align:
    out.append("    {%s}," % ", ".join(str(x) for x in a))
out += ["};", "#endif", ""]
Path(__file__).resolve().parent.parent.joinpath("fw/qr_tables.h").write_text("\n".join(out))
print("wrote fw/qr_tables.h")
