#!/usr/bin/env python3
"""Generate fw/meter_gen.h from meters/*/meter.json (Meter module M0, docs/METER_MODULE_SPEC.md).

Scope of M0, deliberately narrow: this replaces only the hand-maintained VIZ_* enum, the
set_viz[] name table and the viz_order[]/selectable-order remap in fw/player.c and
fw/settingsui.inc. It does NOT touch: the dispatch chain (the per-meter drawing code stays
exactly where it is), meter_afford()'s hardware-spectrum gate list, the X-cycle toast strings,
or fw/meter_thumbs.h (which documents itself as hand-authored source of truth, not
regeneratable -- see tools/gen_meter_thumbs.py's own note).

Each meters/<key>/meter.json carries:
    key         directory/manifest name, lower_snake
    enum        the VIZ_* C identifier
    index       its FIXED enum position (viz_mode persists as this index on real hardware;
                never reorder these once shipped)
    name        the settings-list / set_viz[] label ("-" for a retired, code-free slot)
    selectable  true if it appears in the Settings > Meter list and the X-cycle
    sel_index   position in viz_order[] (only when selectable)
    retired     true for a slot kept only so old saved indices keep resolving (optional)
    needs_hw_spec  true if this meter is gated in meter_afford()'s caller list (informational
                   only in M0 -- the gate list itself is not generated yet)

Usage: python3 tools/gen_meters.py [--dir meters] [--out fw/meter_gen.h] [--check]
--check regenerates into a temp file and diffs against --out (used by make test-host);
exits non-zero and prints a diff-like message if they differ.
"""
import argparse
import glob
import json
import os
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_meters(meters_dir):
    paths = sorted(glob.glob(os.path.join(meters_dir, "*", "meter.json")))
    if not paths:
        raise SystemExit(f"no meter.json files found under {meters_dir}")
    meters = []
    for p in paths:
        with open(p) as f:
            m = json.load(f)
        for req in ("key", "enum", "index", "name", "selectable"):
            if req not in m:
                raise SystemExit(f"{p}: missing required field {req!r}")
        m["_path"] = p
        meters.append(m)
    return meters


def validate(meters):
    by_index = sorted(meters, key=lambda m: m["index"])
    indices = [m["index"] for m in by_index]
    if indices != list(range(len(indices))):
        raise SystemExit(f"meter 'index' fields must be exactly 0..{len(indices)-1} with no gaps or "
                          f"duplicates; got {indices}")
    enums = [m["enum"] for m in by_index]
    if len(set(enums)) != len(enums):
        raise SystemExit(f"duplicate enum names: {enums}")

    selectable = [m for m in by_index if m["selectable"]]
    sel_indices = sorted(m["sel_index"] for m in selectable)
    if sel_indices != list(range(len(selectable))):
        raise SystemExit(f"selectable meters' 'sel_index' fields must be exactly "
                          f"0..{len(selectable)-1} with no gaps or duplicates; got {sel_indices}")
    for m in by_index:
        if not m["selectable"] and "sel_index" in m:
            raise SystemExit(f"{m['_path']}: sel_index set on a non-selectable meter")
    return by_index, sorted(selectable, key=lambda m: m["sel_index"])


def render_enum(by_index):
    """The VIZ_* enum. Included where the hand-written enum used to sit, BEFORE anything that
    names a VIZ_* constant (thumb_slot(), the dispatch chain, ...)."""
    lines = []
    lines.append("/* GENERATED by tools/gen_meters.py from meters/NAME/meter.json -- do not edit by hand.")
    lines.append(" * Meter module M0 (docs/METER_MODULE_SPEC.md section 10). Regenerate after editing a")
    lines.append(" * manifest: python3 tools/gen_meters.py")
    lines.append(" *")
    lines.append(" * viz_mode is persisted as an INDEX on real hardware, so a meter's enum position can")
    lines.append(" * NEVER move once shipped -- only append. New meters get the next free index in a new")
    lines.append(" * meters/NAME/meter.json; retired meters keep their slot (selectable: false, name: \"-\").")
    lines.append(" */")
    enum_names = [m["enum"] for m in by_index]
    lines.append("enum { " + f"{enum_names[0]} = 0, " + ", ".join(enum_names[1:]) + ", VIZ_COUNT };")
    lines.append("")
    return "\n".join(lines)


def render_names(by_index):
    """set_viz[]. Included exactly where the hand-written array used to sit (fw/settingsui.inc,
    between the stress/soak choice tables and set_rep[])."""
    lines = []
    lines.append("/* GENERATED by tools/gen_meters.py -- do not edit by hand. Same order as the VIZ_*")
    lines.append(" * enum; a retired slot's label is \"-\". */")
    name_list = ", ".join(json.dumps(m["name"]) for m in by_index)
    lines.append("static const char *const set_viz[] = { " + name_list + " };")
    lines.append("_Static_assert(sizeof(set_viz) / sizeof(set_viz[0]) == VIZ_COUNT,")
    lines.append('               "set_viz[] must name every visualizer");')
    lines.append("")
    return "\n".join(lines)


def render_order(by_sel):
    """VIZ_SEL_COUNT / viz_order[]. Included where the hand-written pair used to sit in
    fw/player.c (after thumb_slot(), before bars_layout/viz_sel_to_mode)."""
    lines = []
    lines.append("/* GENERATED by tools/gen_meters.py -- do not edit by hand. The list (Settings > Meter,")
    lines.append(" * and the X button) is NOT in enum order: this is the owner's chosen order, sel_index")
    lines.append(" * in each manifest. */")
    lines.append(f"#define VIZ_SEL_COUNT {len(by_sel)}u")
    sel_names = ", ".join(m["enum"] for m in by_sel)
    lines.append(f"static const uint8_t viz_order[VIZ_SEL_COUNT] = {{ {sel_names} }};")
    lines.append("")
    return "\n".join(lines)


OUTPUTS = {
    "enum": ("meter_gen_enum.h", render_enum, lambda by_index, by_sel: render_enum(by_index)),
    "names": ("meter_gen_names.h", render_names, lambda by_index, by_sel: render_names(by_index)),
    "order": ("meter_gen_order.h", render_order, lambda by_index, by_sel: render_order(by_sel)),
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default=os.path.join(ROOT, "meters"))
    ap.add_argument("--fw-dir", default=os.path.join(ROOT, "fw"))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    meters = load_meters(args.dir)
    by_index, by_sel = validate(meters)

    ok = True
    for _key, (fname, _renderfn, gen) in OUTPUTS.items():
        text = gen(by_index, by_sel)
        out = os.path.join(args.fw_dir, fname)
        if args.check:
            if not os.path.exists(out):
                print(f"{out} does not exist; run without --check first", file=sys.stderr)
                ok = False
                continue
            with open(out) as f:
                current = f.read()
            if current != text:
                print(f"{out} is stale relative to meters/NAME/meter.json; regenerate with "
                      f"'python3 tools/gen_meters.py'", file=sys.stderr)
                ok = False
            continue
        with open(out, "w") as f:
            f.write(text)
        print(f"wrote {out}")

    if args.check:
        return 0 if ok else 1
    print(f"({len(by_index)} meters, {len(by_sel)} selectable)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
