#!/usr/bin/env python3
"""Generate fw/vu_segment_table.h, the peak-magnitude -> lit-segment lookup table for the MASTER VU meter
(docs/features/meters/METER_VU_MASTERING_SPEC.md section 2.3, fw/vu_master_core.h's vum_peak_to_segments()).

No floating point exists in this firmware (rv32im, no hardware float -- the same reason B-343/B-345 avoided it
for the FLAC/MP3 profiler work), so this offline tool does the one log10 this design needs and bakes the result
into a checked-in table, the same pattern tools/gen_mp3_poly_rom.py and the AA gamma table already use.

    db = 20 * log10(peak / 32768), clamped to -48..0
    lit_segments = round((db + 48) / 2)          # 0..24

peak is the MTR_HEADROOM-scaled 16-bit accumulator (fw/player.c:4500-4502); the table is indexed by peak >> 7,
so it covers the full 0..32767 range in 256 entries (vum_peak_to_segments() clamps any index at or above 256).

Usage: python3 tools/gen_vu_segment_table.py [--out fw/vu_segment_table.h] [--check]
--check regenerates into memory and diffs against --out (wired into make test-host); exits non-zero and prints
a message if they differ.
"""
import argparse
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLE_N = 256
DB_FLOOR = -48.0
DB_CEIL = 0.0
SEGMENTS = 24


def peak_to_db(peak):
    if peak <= 0:
        return DB_FLOOR
    db = 20.0 * math.log10(peak / 32768.0)
    if db < DB_FLOOR:
        db = DB_FLOOR
    if db > DB_CEIL:
        db = DB_CEIL
    return db


def db_to_segments(db):
    seg = round((db + 48.0) / 2.0)
    if seg < 0:
        seg = 0
    if seg > SEGMENTS:
        seg = SEGMENTS
    return seg


def build_table():
    table = []
    for idx in range(TABLE_N):
        # idx is peak >> 7; use the midpoint of the 128-wide bucket [idx*128, idx*128+127] as the
        # representative peak magnitude, same convention as other offline-quantized tables in tools/.
        peak = idx * 128 + 64
        table.append(db_to_segments(peak_to_db(peak)))
    return table


def render(table):
    lines = []
    lines.append("/* GENERATED by tools/gen_vu_segment_table.py -- do not edit by hand.")
    lines.append(" * Peak magnitude (peak_l/peak_r, the MTR_HEADROOM-scaled 16-bit accumulator) to a lit-segment")
    lines.append(" * count 0..24, indexed by peak >> 7 (256 entries over the full 0..32767 range). See")
    lines.append(" * docs/features/meters/METER_VU_MASTERING_SPEC.md section 2.3 and fw/vu_master_core.h's vum_peak_to_segments().")
    lines.append(" * db = 20*log10(peak/32768), clamped -48..0 dBFS; lit = round((db+48)/2), 2 dB/segment. */")
    lines.append(f"#define VU_SEGMENT_TABLE_N {TABLE_N}u")
    lines.append("static const unsigned char vu_db_to_segment[VU_SEGMENT_TABLE_N] = {")
    for row_start in range(0, len(table), 16):
        row = table[row_start:row_start + 16]
        lines.append("    " + ", ".join(str(v) for v in row) + ",")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "fw", "vu_segment_table.h"))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    text = render(build_table())
    if args.check:
        if not os.path.exists(args.out):
            print(f"{args.out} does not exist; run without --check first", file=sys.stderr)
            sys.exit(1)
        with open(args.out) as f:
            current = f.read()
        if current != text:
            print(f"{args.out} is stale relative to tools/gen_vu_segment_table.py; regenerate with "
                  f"'python3 tools/gen_vu_segment_table.py'", file=sys.stderr)
            sys.exit(1)
        print(f"{args.out} is up to date")
        return
    with open(args.out, "w") as f:
        f.write(text)
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
