#!/usr/bin/env python3
"""fw/diag_features.json -> fw/diag_features.h, and the per-build overrides.

  gen_diag_features.py            write fw/diag_features.h
  gen_diag_features.py --check    exit 1 if the header on disk differs from what the manifest generates (make test-host)
  gen_diag_features.py --list     the register as a table (id, kind, converted, depends)
  gen_diag_features.py --cflags DROP [ON]
                                  -D flags for fw/build.sh: DIAG_DROP (comma list) sets TAU_DX_/TAU_FX_<ID>=0, FEATURES_ON sets an 'fx' to 1.
                                  Unknown ids, ids not yet converted, dropping something another kept feature depends on, and turning on a 'dx' are errors.
"""
import json, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
MAN = ROOT / "fw" / "diag_features.json"
OUT = ROOT / "fw" / "diag_features.h"

def load():
    d = json.loads(MAN.read_text())
    feats = {f["id"]: f for f in d["features"]}
    for f in feats.values():
        if f["kind"] not in ("dx", "fx"): sys.exit(f"{f['id']}: kind must be dx or fx")
        for dep in f["depends"]:
            if dep not in feats: sys.exit(f"{f['id']}: depends on unknown {dep}")
    return feats

def macro(f): return "TAU_%s_%s" % (f["kind"].upper(), f["id"].upper())

def header(feats):
    o = ["/* GENERATED by tools/gen_diag_features.py from fw/diag_features.json -- do not edit. The register of Diagnostic-Build-only code: dx = diagnostics,",
         " * fx = features still incubating behind the flag. Every converted feature defaults to TAU_DIAGNOSTIC (the default Diagnostic Build is unchanged) and can be",
         " * overridden by the build: DIAG_DROP=<ids> (off) / FEATURES_ON=<ids> (an fx on in any build). See docs/features/DIAG_FEATURES.md. */",
         "#ifndef TAU_DIAG_FEATURES_H", "#define TAU_DIAG_FEATURES_H",
         "#ifndef TAU_DIAGNOSTIC", "#define TAU_DIAGNOSTIC 0", "#endif"]
    for f in feats.values():
        if f["converted"]:
            o += ["", f"/* {f['kind']}: {f['title']} */", f"#ifndef {macro(f)}", f"#define {macro(f)} TAU_DIAGNOSTIC", "#endif"]
    o += ["", "#endif", ""]
    return "\n".join(o)

def cflags(feats, drop, on):
    drop = [x for x in drop.split(",") if x]; on = [x for x in on.split(",") if x]
    flags = []
    for i in drop + on:
        if i not in feats: sys.exit(f"unknown feature '{i}' (python3 tools/gen_diag_features.py --list)")
        if not feats[i]["converted"]: sys.exit(f"feature '{i}' is classified but not converted yet: its code still hangs off TAU_DIAGNOSTIC, so it cannot be switched on its own")
    for i in on:
        if feats[i]["kind"] != "fx": sys.exit(f"'{i}' is a diagnostic (dx), only features (fx) can be turned on outside the Diagnostic Build")
    for i in drop:
        for g in feats.values():
            if i in g["depends"] and g["id"] not in drop and g["converted"]:
                sys.exit(f"cannot drop '{i}': '{g['id']}' depends on it (drop that too)")
        flags.append(f"-D{macro(feats[i])}=0")
    flags += [f"-D{macro(feats[i])}=1" for i in on]
    return flags

def main():
    feats = load(); a = sys.argv[1:]
    if a[:1] == ["--list"]:
        for f in feats.values(): print(f"{f['id']:20} {f['kind']}  {'converted' if f['converted'] else 'classified':10} deps={','.join(f['depends']) or '-':8} {f['title'][:90]}")
        return
    if a[:1] == ["--cflags"]:
        print(" ".join(cflags(feats, a[1] if len(a) > 1 else "", a[2] if len(a) > 2 else ""))); return
    h = header(feats)
    if a[:1] == ["--check"]:
        if not OUT.exists() or OUT.read_text() != h: sys.exit("fw/diag_features.h is out of date: run python3 tools/gen_diag_features.py")
        print("diag_features.h is up to date"); return
    OUT.write_text(h); print("wrote", OUT)
main()
