#!/usr/bin/env python3
"""Generates fw/halcyon_tab.h: the Halcyon stage tables for the firmware macro layer (B-631, parallel plan A5). Own method; no third-party code.

For each of the six tone stages (tools/lab/halcyon_model.STAGES) and each stage gain from -9.0 to +9.0 dB in 0.5 dB steps (37 steps):
  hal_coef[stage][step][5]   the Q2.22 coefficients (b0 b1 b2 a1 a2) of the analog-matched design (gen_eq_coeffs.design_stage), 24-bit signed in an int32
  hal_mag [stage][step][40]  the QUANTISED stage's magnitude in 1/64 dB at 40 log-spaced frequencies from 20 Hz to 20 kHz (cascade magnitudes add in dB, so the firmware gets the composite
                             response of any control setting by adding six table rows: no trigonometry on the CPU)
  hal_pre [513]              10^(-n/8/20) in Q2.22 for attenuations of n/8 dB, n = 0..512 (64 dB): the peak-safe preamp
Run:  python3 tools/gen_halcyon_tab.py            (writes fw/halcyon_tab.h)    python3 tools/gen_halcyon_tab.py --check   (fails if the file is stale)
"""
import math, os, sys
os.environ["EQ_COEF_BITS"] = "24"                     # Q2.22: must be set before gen_eq_coeffs is imported
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools")); sys.path.insert(0, str(ROOT / "tools" / "lab"))
import gen_eq_coeffs as g
import halcyon_model as m

NSTEP, NGRID = 37, 40
FREQS = [20.0 * (1000.0 ** (k / (NGRID - 1.0))) for k in range(NGRID)]
assert g.CW == 24 and g.QF == 22


def build():
    coef, mag = [], []
    for (name, kind, f0, q) in m.STAGES:
        cs, ms = [], []
        for i in range(NSTEP):
            gd = (i - 18) / 2.0
            c = tuple(g.quantise(v, name, []) for v in g.design_stage(kind, f0, q, gd, True))
            if not g.stable([c]):
                raise SystemExit(f"{name} {gd:+.1f} dB unstable at Q2.22")
            cs.append(c)
            ms.append([int(round(g.response_db([c], f) * 64.0)) for f in FREQS])
        coef.append(cs); mag.append(ms)
    pre = [int(round(10 ** (-n / 8.0 / 20.0) * (1 << g.QF))) for n in range(513)]
    return coef, mag, pre


def render():
    coef, mag, pre = build()
    o = ["/* GENERATED by tools/gen_halcyon_tab.py -- DO NOT EDIT. Halcyon stage tables, Q2.22, see that file's header. */",
         "#ifndef TAU_HALCYON_TAB_H", "#define TAU_HALCYON_TAB_H", "#include <stdint.h>",
         f"#define HAL_NSTAGE {len(m.STAGES)}", f"#define HAL_NSTEP {NSTEP}", f"#define HAL_NGRID {NGRID}",
         "#ifndef HAL_TAB", "#define HAL_TAB   /* the firmware defines this as COLD_DATA: the tables (about 24 KB) live in PSRAM, never in on-chip RAM */", "#endif", f"#define HAL_NPRESET {len(m.PRESETS)}", ""]
    o.append("HAL_TAB static const int32_t hal_coef[HAL_NSTAGE][HAL_NSTEP][5] = {")
    for s, cs in enumerate(coef):
        o.append("  {  /* " + m.STAGES[s][0] + " */")
        for c in cs:
            o.append("    {" + ",".join(str(v) for v in c) + "},")
        o.append("  },")
    o.append("};")
    o.append("HAL_TAB static const int16_t hal_mag[HAL_NSTAGE][HAL_NSTEP][HAL_NGRID] = {")
    for s, ms in enumerate(mag):
        o.append("  {")
        for row in ms:
            o.append("    {" + ",".join(str(v) for v in row) + "},")
        o.append("  },")
    o.append("};")
    o.append("HAL_TAB static const int32_t hal_pre[513] = {")
    for i in range(0, 513, 8):
        o.append("  " + ",".join(str(v) for v in pre[i:i + 8]) + ",")
    o.append("};")
    o.append("/* the built-in control presets (tools/lab/halcyon_model.py PRESETS): name and warmth, bass, vocal, punch, sibilance, air */")
    o.append("HAL_TAB static const char hal_preset_name[HAL_NPRESET][11] = {" + ",".join('"%s"' % p[0] for p in m.PRESETS) + "};")
    o.append("HAL_TAB static const int8_t hal_preset_ctl[HAL_NPRESET][6] = {")
    for p in m.PRESETS:
        o.append("  {" + ",".join(str(p[1][k]) for k in m.MACROS) + "},  /* " + p[0] + " */")
    o.append("};")
    o.append("#endif")
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    out = ROOT / "fw" / "halcyon_tab.h"
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if out.exists() and out.read_text() == text else "fw/halcyon_tab.h is stale: run tools/gen_halcyon_tab.py")
    out.write_text(text)
    print(f"wrote {out} ({len(text)} bytes)")
