#!/usr/bin/env python3
"""Layered Wave meter tables (docs/features/meters/LAYERED_WAVE_METER_SPEC.md): ONE generator for the firmware (fw/layered_wave_tables.h, cold
data) and the JS twin (tools/meters/preview/lw_tables.js), so the two can never disagree. All integer at run time; floating point exists only here.

    python3 tools/gen_layered_wave_tables.py          # write both
    python3 tools/gen_layered_wave_tables.py --check  # fail if either is stale
"""
import math, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
H_OUT, J_OUT = ROOT / "fw" / "layered_wave_tables.h", ROOT / "tools" / "meters" / "preview" / "lw_tables.js"
N = 65                                                    # window samples across the width, a = i/64


def win_hist(a, t):                                       # history view: gentle roll-off toward the tail, pointed head
    w = (1 - a ** (1 + 3 * (1 - t / 100))) * (math.sin(a / 0.07 * math.pi / 2) if a < 0.07 else 1)
    return max(0, min(255, int(w * 255 + 0.5)))


def win_spec(a, t):                                       # spectrum view: both ends pointed
    return max(0, min(255, int((math.sin(math.pi * a) ** (0.6 * t / 100)) * 255 + 0.5)))


def tables():
    hist = [[win_hist(i / 64, 5 * q) for i in range(N)] for q in range(1, 21)]      # taper_q = 1..20 (taper 5..100); 0 = no taper
    spec = [[win_spec(i / 64, 5 * q) for i in range(N)] for q in range(1, 21)]
    mul = [int(256 * 1.6 ** (j / 2) + 0.5) for j in range(-5, 6)]                    # layer time-constant multipliers, Q8, j = n-1-2k
    def rot(deg):                                         # CSS hue-rotate matrix (grey stays grey), Q10
        c, s = math.cos(math.radians(deg)), math.sin(math.radians(deg))
        m = [0.213 + c * 0.787 - s * 0.213, 0.715 - c * 0.715 - s * 0.715, 0.072 - c * 0.072 + s * 0.928,
             0.213 - c * 0.213 + s * 0.143, 0.715 + c * 0.285 + s * 0.140, 0.072 - c * 0.072 - s * 0.283,
             0.213 - c * 0.213 - s * 0.787, 0.715 - c * 0.715 + s * 0.715, 0.072 + c * 0.928 + s * 0.072]
        return [int(round(v * 1024)) for v in m]
    gain = [int(round(256 * 10 ** (db / 20))) for db in range(-18, 20)]               # layer gain -18..+19 dB, Q8 (index db + 18; 38 entries)
    return hist, spec, mul, [rot(-30), rot(30), rot(180)], gain


def render():
    hist, spec, mul, hue, gain = tables()
    row = lambda r: "    { " + ", ".join(str(v) for v in r) + " },"
    c = ["/* GENERATED by tools/gen_layered_wave_tables.py -- do not edit. Layered Wave meter (fw/layered_wave.inc): taper windows (0..255) for taper 5..100, ",
         " * layer time-constant multipliers (Q8) and the three hue-rotation matrices (Q10). Same numbers as tools/meters/preview/lw_tables.js. */",
         "static const uint8_t lw_win_hist[20][65] COLD_DATA = {"] + [row(r) for r in hist] + ["};",
         "static const uint8_t lw_win_spec[20][65] COLD_DATA = {"] + [row(r) for r in spec] + ["};",
         "static const uint16_t lw_mul_q8[11] COLD_DATA = { " + ", ".join(str(v) for v in mul) + " };",
         "static const int16_t lw_hue[3][9] COLD_DATA = {"] + [row(r) for r in hue] + ["};",
         "static const uint16_t lw_gain_q8[38] COLD_DATA = { " + ", ".join(str(v) for v in gain) + " };", ""]
    j = ["/* GENERATED by tools/gen_layered_wave_tables.py -- do not edit. Same numbers as fw/layered_wave_tables.h. */",
         "(function (root) {",
         "  const T = { winHist: " + str(hist) + ",", "    winSpec: " + str(spec) + ",",
         "    mulQ8: " + str(mul) + ", hue: " + str(hue) + ", gainQ8: " + str(gain) + " };",
         "  if (typeof module !== 'undefined') module.exports = T; else root.LwTables = T;",
         "})(typeof globalThis !== 'undefined' ? globalThis : window);", ""]
    return "\n".join(c), "\n".join(j)


def main():
    h, j = render()
    if "--check" in sys.argv:
        ok = H_OUT.exists() and H_OUT.read_text() == h and J_OUT.exists() and J_OUT.read_text() == j
        if not ok:
            print("layered wave tables are stale; run python3 tools/gen_layered_wave_tables.py", file=sys.stderr)
        return 0 if ok else 1
    H_OUT.write_text(h); J_OUT.write_text(j); print("wrote", H_OUT, J_OUT)
    return 0


sys.exit(main())
