#!/usr/bin/env python3
"""Generate the ROM tables of the hardware MP3 window unit (src/fpga/core/tau_mp3_poly.sv, B-292) and a C header for the golden model.

Sources of truth (nothing is typed in by hand):
  * the 264 window coefficients: parsed from third_party/libhelix-mp3/real/trigtabs.c (polyCoef[]);
  * the tap map (which FDCT32 output word, by age and push index, each window tap reads): derived from Helix's REAL FDCT32/PolyphaseStereo by
    sim/mp3_poly_map.c (built here against copies of Helix's sources with the portable shim and an instrumented FDCT32).

Outputs:  --sv PATH  a SystemVerilog include with `poly_tap(i)` and `poly_coef(i)` ROM functions;  --h PATH  a C header for sim/mp3_poly_model.c.
The tap index is  i = row*16 + tap  (row 0..16, tap 0..15; the sample-16 row 16 uses taps 0..7 only), the value is {age[3:0], P[4:0]}.
"""
import argparse, re, shutil, subprocess, sys, tempfile
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
H = ROOT / "third_party/libhelix-mp3"


def build_map():
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        for f in ("polyphase.c", "trigtabs.c"): shutil.copy(H / "real" / f, td / f)
        shutil.copy(ROOT / "sim/helix_host/assembly.h", td / "assembly.h")
        s = (H / "real/dct32.c").read_text()
        assert s.count("d[0] = d[8] = s;") == 33
        s = s.replace("d[0] = d[8] = s;", "WRLOG(d, s);")
        s = s.replace('#include "assembly.h"', '#include "assembly.h"\nextern int wlog[64], wn;\n#define WRLOG(d, s) do { d[0] = d[8] = (s); wlog[wn++] = (s); } while (0)', 1)
        (td / "dct32.c").write_text(s)
        exe = td / "map"
        r = subprocess.run(["cc", "-std=gnu11", "-O1", "-w", "-I", str(td), "-I", str(H / "pub"), "-I", str(H / "real"), "-o", str(exe),
                            str(ROOT / "sim/mp3_poly_map.c"), str(td / "dct32.c"), str(td / "polyphase.c"), str(td / "trigtabs.c")], capture_output=True, text=True)
        if r.returncode: sys.exit(r.stderr)
        p = subprocess.run([str(exe)], capture_output=True, text=True)
        if p.returncode: sys.exit("tap map derivation failed:\n" + p.stdout)
    taps, on = {}, False
    for line in p.stdout.splitlines():
        if line == "MAP BEGIN": on = True; continue
        if line == "MAP END": on = False; continue
        if on:
            r_, t, a, pi = map(int, line.split()); taps[(r_, t)] = (a, pi)
    assert len(taps) == 17 * 16 - 8, len(taps)
    return taps


def coefs():
    s = (H / "real/trigtabs.c").read_text()
    i = s.index("const int polyCoef[264]")
    body = s[s.index("{", i) + 1:s.index("};", i)]
    v = [int(x, 16) for x in re.findall(r"0x[0-9a-fA-F]{8}", body)]
    assert len(v) == 264, len(v)
    return [x - (1 << 32) if x >= 1 << 31 else x for x in v]


def render_sv(taps, cf):
    o = ["// GENERATED by tools/gen_mp3_poly_rom.py from Helix's trigtabs.c (polyCoef) and the tap map derived from Helix's FDCT32/PolyphaseStereo",
         "// (sim/mp3_poly_map.c). Do not edit by hand: sim/test_mp3_poly_model.py fails if this file differs from a fresh generation.",
         "", "// tap i = row*16 + tap (rows 0..16; row 16 has taps 0..7) -> {age[3:0], P[4:0]}",
         "function automatic [8:0] poly_tap(input [8:0] i);", "    case (i)"]
    for (r, t), (a, p) in sorted(taps.items()):
        o.append(f"        9'd{r*16+t}: poly_tap = {{4'd{a}, 5'd{p}}};")
    o += ["        default: poly_tap = 9'd0;", "    endcase", "endfunction", "",
          "// window coefficients (signed, about 20 bits used): polyCoef[i]", "function automatic signed [31:0] poly_coef(input [8:0] i);", "    case (i)"]
    for i, v in enumerate(cf):
        o.append(f"        9'd{i}: poly_coef = {'-' if v < 0 else ''}32'sd{abs(v)};")
    o += ["        default: poly_coef = 32'sd0;", "    endcase", "endfunction", ""]
    return "\n".join(o)


def render_h(taps, cf):
    o = ["/* GENERATED by tools/gen_mp3_poly_rom.py -- do not edit. */", "static const unsigned char poly_tap_age[272] = {"]
    ages, ps = [0] * 272, [0] * 272
    for (r, t), (a, p) in taps.items(): ages[r * 16 + t] = a; ps[r * 16 + t] = p
    o.append(",".join(map(str, ages)) + "};")
    o.append("static const unsigned char poly_tap_p[272] = {" + ",".join(map(str, ps)) + "};")
    o.append("static const int poly_coef_tab[264] = {" + ",".join(str(v) for v in cf) + "};")
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--sv", type=Path); ap.add_argument("--h", type=Path)
    a = ap.parse_args()
    taps, cf = build_map(), coefs()
    if a.sv: a.sv.write_text(render_sv(taps, cf))
    if a.h: a.h.write_text(render_h(taps, cf))
