// GENERATED by tools/gen_eq_coeffs.py --verilog -- DO NOT EDIT.
//
// Q2.22 signed (24-bit), Fs = 48000 Hz. Five bands per preset,
// five coefficients per band, in the order b0 b1 b2 a1 a2.
// Index: ((preset*5) + band)*5 + k
//
// The difference equation SUBTRACTS a1 and a2:
//   y = b0*x + b1*x1 + b2*x2 - a1*y1 - a2*y2

// ---- FLAT (preset 0), preamp -0.00 dB
//   lowshelf      80 Hz
crom[  0] = 24'sd4194304;  // b0
crom[  1] = -24'sd8314562;  // b1
crom[  2] = 24'sd4120714;  // b2
crom[  3] = -24'sd8314562;  // a1
crom[  4] = 24'sd4120714;  // a2
//   peak         250 Hz
crom[  5] = 24'sd4194304;  // b0
crom[  6] = -24'sd8249164;  // b1
crom[  7] = 24'sd4059279;  // b2
crom[  8] = -24'sd8249164;  // a1
crom[  9] = 24'sd4059279;  // a2
//   peak        1000 Hz
crom[ 10] = 24'sd4194304;  // b0
crom[ 11] = -24'sd7807313;  // b1
crom[ 12] = 24'sd3680378;  // b2
crom[ 13] = -24'sd7807313;  // a1
crom[ 14] = 24'sd3680378;  // a2
//   peak        4000 Hz
crom[ 15] = 24'sd4194304;  // b0
crom[ 16] = -24'sd5811798;  // b1
crom[ 17] = 24'sd2516582;  // b2
crom[ 18] = -24'sd5811798;  // a1
crom[ 19] = 24'sd2516582;  // a2
//   highshelf  12000 Hz
crom[ 20] = 24'sd4194304;  // b0
crom[ 21] = 24'sd0      ;  // b1
crom[ 22] = 24'sd351987 ;  // b2
crom[ 23] = 24'sd0      ;  // a1
crom[ 24] = 24'sd351987 ;  // a2
// ---- BASS (preset 1), preamp -2.09 dB
//   lowshelf      80 Hz
crom[ 25] = 24'sd4207288;  // b0
crom[ 26] = -24'sd8325565;  // b1
crom[ 27] = 24'sd4118922;  // b2
crom[ 28] = -24'sd8325726;  // a1
crom[ 29] = 24'sd4131745;  // a2
//   peak         250 Hz
crom[ 30] = 24'sd4217798;  // b0
crom[ 31] = -24'sd8270278;  // b1
crom[ 32] = 24'sd4056910;  // b2
crom[ 33] = -24'sd8270278;  // a1
crom[ 34] = 24'sd4080404;  // a2
//   peak        1000 Hz
crom[ 35] = 24'sd4194304;  // b0
crom[ 36] = -24'sd7807313;  // b1
crom[ 37] = 24'sd3680378;  // b2
crom[ 38] = -24'sd7807313;  // a1
crom[ 39] = 24'sd3680378;  // a2
//   peak        4000 Hz
crom[ 40] = 24'sd4098805;  // b0
crom[ 41] = -24'sd5743731;  // b1
crom[ 42] = 24'sd2533484;  // b2
crom[ 43] = -24'sd5743731;  // a1
crom[ 44] = 24'sd2437985;  // a2
//   highshelf  12000 Hz
crom[ 45] = 24'sd4194304;  // b0
crom[ 46] = 24'sd0      ;  // b1
crom[ 47] = 24'sd351987 ;  // b2
crom[ 48] = 24'sd0      ;  // a1
crom[ 49] = 24'sd351987 ;  // a2
// ---- ROCK (preset 2), preamp -2.02 dB
//   lowshelf      80 Hz
crom[ 50] = 24'sd4205076;  // b0
crom[ 51] = -24'sd8323936;  // b1
crom[ 52] = 24'sd4119468;  // b2
crom[ 53] = -24'sd8324069;  // a1
crom[ 54] = 24'sd4130107;  // a2
//   peak         250 Hz
crom[ 55] = 24'sd4209911;  // b0
crom[ 56] = -24'sd8263629;  // b1
crom[ 57] = 24'sd4058145;  // b2
crom[ 58] = -24'sd8263629;  // a1
crom[ 59] = 24'sd4073752;  // a2
//   peak        1000 Hz
crom[ 60] = 24'sd4135445;  // b0
crom[ 61] = -24'sd7749383;  // b1
crom[ 62] = 24'sd3680807;  // b2
crom[ 63] = -24'sd7749383;  // a1
crom[ 64] = 24'sd3621948;  // a2
//   peak        4000 Hz
crom[ 65] = 24'sd4392190;  // b0
crom[ 66] = -24'sd5941014;  // b1
crom[ 67] = 24'sd2467902;  // b2
crom[ 68] = -24'sd5941014;  // a1
crom[ 69] = 24'sd2665788;  // a2
//   highshelf  12000 Hz
crom[ 70] = 24'sd5280316;  // b0
crom[ 71] = -24'sd656831;  // b1
crom[ 72] = 24'sd450031 ;  // b2
crom[ 73] = 24'sd521740 ;  // a1
crom[ 74] = 24'sd357473 ;  // a2
// ---- POP (preset 3), preamp -0.89 dB
//   lowshelf      80 Hz
crom[ 75] = 24'sd4192173;  // b0
crom[ 76] = -24'sd8312413;  // b1
crom[ 77] = 24'sd4120671;  // b2
crom[ 78] = -24'sd8312387;  // a1
crom[ 79] = 24'sd4118566;  // a2
//   peak         250 Hz
crom[ 80] = 24'sd4194304;  // b0
crom[ 81] = -24'sd8249164;  // b1
crom[ 82] = 24'sd4059279;  // b2
crom[ 83] = -24'sd8249164;  // a1
crom[ 84] = 24'sd4059279;  // a2
//   peak        1000 Hz
crom[ 85] = 24'sd4254000;  // b0
crom[ 86] = -24'sd7859678;  // b1
crom[ 87] = 24'sd3673498;  // b2
crom[ 88] = -24'sd7859678;  // a1
crom[ 89] = 24'sd3733195;  // a2
//   peak        4000 Hz
crom[ 90] = 24'sd4495017;  // b0
crom[ 91] = -24'sd6002194;  // b1
crom[ 92] = 24'sd2435719;  // b2
crom[ 93] = -24'sd6002194;  // a1
crom[ 94] = 24'sd2736432;  // a2
//   highshelf  12000 Hz
crom[ 95] = 24'sd4442832;  // b0
crom[ 96] = -24'sd138579;  // b1
crom[ 97] = 24'sd373209 ;  // b2
crom[ 98] = 24'sd130827 ;  // a1
crom[ 99] = 24'sd352332 ;  // a2
// ---- JAZZ (preset 4), preamp -0.93 dB
//   lowshelf      80 Hz
crom[100] = 24'sd4200725;  // b0
crom[101] = -24'sd8320443;  // b1
crom[102] = 24'sd4120261;  // b2
crom[103] = -24'sd8320522;  // a1
crom[104] = 24'sd4126602;  // a2
//   peak         250 Hz
crom[105] = 24'sd4202088;  // b0
crom[106] = -24'sd8256598;  // b1
crom[107] = 24'sd4058933;  // b2
crom[108] = -24'sd8256598;  // a1
crom[109] = 24'sd4066717;  // a2
//   peak        1000 Hz
crom[110] = 24'sd4194304;  // b0
crom[111] = -24'sd7807313;  // b1
crom[112] = 24'sd3680378;  // b2
crom[113] = -24'sd7807313;  // a1
crom[114] = 24'sd3680378;  // a2
//   peak        4000 Hz
crom[115] = 24'sd4098805;  // b0
crom[116] = -24'sd5743731;  // b1
crom[117] = 24'sd2533484;  // b2
crom[118] = -24'sd5743731;  // a1
crom[119] = 24'sd2437985;  // a2
//   highshelf  12000 Hz
crom[120] = 24'sd4706086;  // b0
crom[121] = -24'sd293403;  // b1
crom[122] = 24'sd396482 ;  // b2
crom[123] = 24'sd261496 ;  // a1
crom[124] = 24'sd353365 ;  // a2
// ---- CLASSICAL (preset 5), preamp -0.49 dB
//   lowshelf      80 Hz
crom[125] = 24'sd4198575;  // b0
crom[126] = -24'sd8318572;  // b1
crom[127] = 24'sd4120509;  // b2
crom[128] = -24'sd8318625;  // a1
crom[129] = 24'sd4124728;  // a2
//   peak         250 Hz
crom[130] = 24'sd4194304;  // b0
crom[131] = -24'sd8249164;  // b1
crom[132] = 24'sd4059279;  // b2
crom[133] = -24'sd8249164;  // a1
crom[134] = 24'sd4059279;  // a2
//   peak        1000 Hz
crom[135] = 24'sd4194304;  // b0
crom[136] = -24'sd7807313;  // b1
crom[137] = 24'sd3680378;  // b2
crom[138] = -24'sd7807313;  // a1
crom[139] = 24'sd3680378;  // a2
//   peak        4000 Hz
crom[140] = 24'sd4005334;  // b0
crom[141] = -24'sd5673347;  // b1
crom[142] = 24'sd2545684;  // b2
crom[143] = -24'sd5673347;  // a1
crom[144] = 24'sd2356713;  // a2
//   highshelf  12000 Hz
crom[145] = 24'sd4984940;  // b0
crom[146] = -24'sd465717;  // b1
crom[147] = 24'sd422015 ;  // b2
crom[148] = 24'sd391852 ;  // a1
crom[149] = 24'sd355081 ;  // a2
// ---- VOCAL (preset 6), preamp -0.41 dB
//   lowshelf      80 Hz
crom[150] = 24'sd4187893;  // b0
crom[151] = -24'sd8307805;  // b1
crom[152] = 24'sd4120295;  // b2
crom[153] = -24'sd8307726;  // a1
crom[154] = 24'sd4113963;  // a2
//   peak         250 Hz
crom[155] = 24'sd4186534;  // b0
crom[156] = -24'sd8241304;  // b1
crom[157] = 24'sd4059184;  // b2
crom[158] = -24'sd8241304;  // a1
crom[159] = 24'sd4051415;  // a2
//   peak        1000 Hz
crom[160] = 24'sd4284373;  // b0
crom[161] = -24'sd7883920;  // b1
crom[162] = 24'sd3667577;  // b2
crom[163] = -24'sd7883920;  // a1
crom[164] = 24'sd3757646;  // a2
//   peak        4000 Hz
crom[165] = 24'sd4392190;  // b0
crom[166] = -24'sd5941014;  // b1
crom[167] = 24'sd2467902;  // b2
crom[168] = -24'sd5941014;  // a1
crom[169] = 24'sd2665788;  // a2
//   highshelf  12000 Hz
crom[170] = 24'sd4194304;  // b0
crom[171] = 24'sd0      ;  // b1
crom[172] = 24'sd351987 ;  // b2
crom[173] = 24'sd0      ;  // a1
crom[174] = 24'sd351987 ;  // a2
// ---- TREBLE (preset 7), preamp -1.17 dB
//   lowshelf      80 Hz
crom[175] = 24'sd4194304;  // b0
crom[176] = -24'sd8314562;  // b1
crom[177] = 24'sd4120714;  // b2
crom[178] = -24'sd8314562;  // a1
crom[179] = 24'sd4120714;  // a2
//   peak         250 Hz
crom[180] = 24'sd4194304;  // b0
crom[181] = -24'sd8249164;  // b1
crom[182] = 24'sd4059279;  // b2
crom[183] = -24'sd8249164;  // a1
crom[184] = 24'sd4059279;  // a2
//   peak        1000 Hz
crom[185] = 24'sd4194304;  // b0
crom[186] = -24'sd7807313;  // b1
crom[187] = 24'sd3680378;  // b2
crom[188] = -24'sd7807313;  // a1
crom[189] = 24'sd3680378;  // a2
//   peak        4000 Hz
crom[190] = 24'sd4392190;  // b0
crom[191] = -24'sd5941014;  // b1
crom[192] = 24'sd2467902;  // b2
crom[193] = -24'sd5941014;  // a1
crom[194] = 24'sd2665788;  // a2
//   highshelf  12000 Hz
crom[195] = 24'sd5924612;  // b0
crom[196] = -24'sd1101070;  // b1
crom[197] = 24'sd514493 ;  // b2
crom[198] = 24'sd779498 ;  // a1
crom[199] = 24'sd364233 ;  // a2

prom[0] = 24'sd4194304;  // FLAT       -0.00 dB
prom[1] = 24'sd3295913;  // BASS       -2.09 dB
prom[2] = 24'sd3322597;  // ROCK       -2.02 dB
prom[3] = 24'sd3787782;  // POP        -0.89 dB
prom[4] = 24'sd3769681;  // JAZZ       -0.93 dB
prom[5] = 24'sd3962239;  // CLASSICAL  -0.49 dB
prom[6] = 24'sd4001046;  // VOCAL      -0.41 dB
prom[7] = 24'sd3667242;  // TREBLE     -1.17 dB
