// =============================================================================
// tau_mp3_poly.sv -- the MP3 synthesis window (Helix PolyphaseStereo) in hardware. B-292; design: docs/MP3_FILTERBANK_KERNEL_DESIGN.md.
//
// The CPU still runs FDCT32. Its 32 unique output words per slot and channel are PUSHED here (in the order FDCT32's final stage produces them:
// P0 = sample 0, P1..16 = samples 16..31, P17..31 = samples 15..1; the duplicate write Helix makes for sample 16 is skipped). This unit keeps
// the last 16 slots of both channels in ONE 1024 x 32 array (an M10K quartet), runs Helix's 512-tap window over them with the same 64-bit
// multiply-accumulate, rounding, arithmetic shift and clip, and leaves 32 stereo PCM words for the CPU to read.
// Bit-exact with Helix by construction: sim/mp3_poly_model.c is the golden model (equal to the real PolyphaseStereo on 190 slots incl. clipped
// samples) and sim/tb_tau_mp3_poly.v replays its vectors against this RTL.
//
// TAP MAP AND COEFFICIENTS come from tau_mp3_poly_rom.svh, GENERATED by tools/gen_mp3_poly_rom.py from Helix's own tables and from Helix's own
// FDCT32/PolyphaseStereo (never typed in).
//
// TIMING STYLE (the project's rule): one small operation per clock in a sequenced machine, registered between every stage; the multiplier has its
// own input and product registers, so nothing chains a 32x32 multiply into a 64-bit add in one cycle. About 16 clocks per macro-step, 136 macro-steps
// per channel per slot: roughly 4,400 clocks (73 us at 60 MHz) per stereo slot, 36 slots per MP3 frame = about 10 percent of hardware time.
//
// MMIO-facing protocol (mp3_soc.v wires the registers): push_we with push_data, 64 times (channel 0's 32 words, then channel 1's); then go; poll busy;
// then out_idx_we / rd_data for the 32 PCM words ({R sample, L sample}). STEREO ONLY: a mono stream is left to the software path.
// =============================================================================
module tau_mp3_poly #(
    parameter integer BUG = 0        // mutation hooks for the testbench: 1 no rounding constant, 2 +c2 instead of -c2, 3 age off by one, 4 no clip
)(
    input  wire        clk,
    input  wire        rst,
    input  wire        clear,           // pulse: forget both histories (a new track); zeroes the array, busy for 1,024 clocks
    input  wire        push_we,
    input  wire [31:0] push_data,
    input  wire        go,
    output wire        busy,
    input  wire        out_idx_we,
    input  wire [4:0]  out_idx,
    output reg  [31:0] rd_data,
    output reg  [15:0] slots_done       // slots computed since reset, for the status word
);
`include "tau_mp3_poly_rom.svh"

    // ---- history: [channel][slot ring 0..15][P 0..31] ----
    (* ramstyle = "M10K, no_rw_check" *) reg [31:0] ring [0:1023];
    reg [3:0] head0, head1;
    reg        busy_r;
    reg [6:0] pc;                                  // words pushed for the pending slot (0..64)
    wire      pch  = pc[5];
    wire [4:0] pp  = pc[4:0];
    wire [3:0] hcur = pch ? head1 : head0;
    wire [3:0] hnext = hcur + 4'd1;
    wire [3:0] wslot = (pp == 5'd0) ? hnext : hcur;
    wire       push_ok = push_we && !busy_r && (pc != 7'd64);
    reg        zeroing;                            // a clear is running: the whole array is written with 0 (Helix's vbuf starts at 0)
    reg [9:0]  zaddr;
    always @(posedge clk) begin
        if (push_ok) ring[{pch, wslot, pp}] <= push_data;
        else if (zeroing) ring[zaddr] <= 32'd0;
    end

    reg [9:0] raddr;
    reg [31:0] rd;
    always @(posedge clk) rd <= ring[raddr];

    // ---- results: [channel][sample] ----
    (* ramstyle = "logic" *) reg [15:0] outbuf0 [0:31];
    (* ramstyle = "logic" *) reg [15:0] outbuf1 [0:31];
    always @(posedge clk) if (out_idx_we) rd_data <= {outbuf1[out_idx], outbuf0[out_idx]};

    // ---- the sequencer ----
    localparam [3:0] S_IDLE = 0, S_TAPS = 1, S_RAM_LO = 2, S_LATCH_LO = 3, S_RAM_HI = 4, S_LATCH_HI = 5, S_MAC_A = 6, S_MAC_B = 7, S_MAC_C = 8,
                     S_NEXT = 9, S_STORE = 10, S_DONE = 11, S_CLR = 12;
    reg [3:0]  st;
    assign busy = busy_r;
    reg        ch;                                  // channel being computed
    reg [4:0]  grp;                                 // group 0 = sample 0, 1 = sample 16, 2..16 = samples (grp-1) and 32-(grp-1)
    reg [2:0]  x;                                   // macro index 0..7
    reg [1:0]  m;                                   // MAC within the macro
    reg [3:0]  age_lo, age_hi;
    reg [4:0]  p_lo, p_hi;
    reg signed [31:0] c1, c2;
    reg signed [31:0] vlo, vhi;
    reg signed [31:0] a_r, b_r;
    reg signed [63:0] prod;
    reg signed [63:0] acc1, acc2;
    localparam signed [63:0] RND = (BUG == 1) ? 64'sd0 : 64'sd33554432;   // 1 << (NFRAC-1 + 32-CSHIFT) = 1 << 25

    wire g0  = (grp == 5'd0);
    wire g16 = (grp == 5'd1);
    wire [3:0] irow = grp[3:0] - 4'd1;              // i = 1..15 for grp 2..16 (grp-1 = i)
    wire [4:0] row = g0 ? 5'd0 : (g16 ? 5'd16 : (grp - 5'd1));
    wire [8:0] cbase = g0 ? 9'd0 : (g16 ? 9'd256 : (9'd16 + {1'b0, irow - 4'd1, 4'b0000}));
    wire [3:0] nmac_m1 = g0 ? 4'd1 : (g16 ? 4'd0 : 4'd3);     // MACs per macro minus one

    function automatic [9:0] raddr_of(input c, input [3:0] h, input [3:0] age, input [4:0] p);
        raddr_of = {c, (h - age + ((BUG == 3) ? 4'd1 : 4'd0)), p};
    endfunction
    wire [3:0] hh = ch ? head1 : head0;

    // clip16(sum): the (int) cast keeps bits 51:20, then >> NFRAC (6), then clip
    function automatic [15:0] clip16(input signed [63:0] s);
        reg signed [31:0] t; reg signed [31:0] u;
        begin
            t = s[51:20];
            u = t >>> 6;
            if (BUG == 4) clip16 = u[15:0];
            else if (u > 32'sd32767) clip16 = 16'h7FFF;
            else if (u < -32'sd32768) clip16 = 16'h8000;
            else clip16 = u[15:0];
        end
    endfunction

    // which word/coefficient feeds MAC m of a macro:  group 0: (lo,c1,+) then (hi,c2,-) into acc1;  group 16: (lo,c1,+) into acc1;
    // other groups: (lo,c1,+ acc1) (lo,c2,+ acc2) (hi,c2,- acc1) (hi,c1,+ acc2)
    wire        use_hi   = g0 ? (m == 2'd1) : (g16 ? 1'b0 : (m[1] == 1'b1));
    wire        use_c2   = g0 ? (m == 2'd1) : (g16 ? 1'b0 : (m == 2'd1 || m == 2'd2));
    wire        negate   = g0 ? (m == 2'd1) : (g16 ? 1'b0 : (m == 2'd2));
    wire        to_acc2  = (!g0 && !g16) && (m == 2'd1 || m == 2'd3);
    wire signed [31:0] coef_sel = use_c2 ? c2 : c1;

    always @(posedge clk) begin
        if (rst) begin
            st <= S_IDLE; busy_r <= 1'b0; head0 <= 4'd0; head1 <= 4'd0; pc <= 7'd0; slots_done <= 16'd0;
            ch <= 1'b0; grp <= 5'd0; x <= 3'd0; m <= 2'd0; zeroing <= 1'b0; zaddr <= 10'd0;
        end else begin
            if (push_ok) begin
                if (pp == 5'd0) begin if (pch) head1 <= hnext; else head0 <= hnext; end
                pc <= pc + 7'd1;
            end
            case (st)
            S_IDLE: if (clear) begin
                head0 <= 4'd0; head1 <= 4'd0; pc <= 7'd0; zeroing <= 1'b1; zaddr <= 10'd0; busy_r <= 1'b1; st <= S_CLR;
            end else if (go && pc == 7'd64) begin
                busy_r <= 1'b1; ch <= 1'b0; grp <= 5'd0; x <= 3'd0; m <= 2'd0; st <= S_TAPS;
                acc1 <= RND; acc2 <= RND;
            end
            S_TAPS: begin                                      // registered ROM lookups for this macro
                {age_lo, p_lo} <= poly_tap({row, 4'd0} + {6'd0, x});
                {age_hi, p_hi} <= poly_tap({row, 4'd0} + 9'd8 + {6'd0, x});
                if (g16) begin c1 <= poly_coef(cbase + {6'd0, x}); c2 <= 32'sd0; end
                else begin c1 <= poly_coef(cbase + {5'd0, x, 1'b0}); c2 <= poly_coef(cbase + {5'd0, x, 1'b1}); end
                st <= S_RAM_LO;
            end
            S_RAM_LO:   begin raddr <= raddr_of(ch, hh, age_lo, p_lo); st <= S_LATCH_LO; end
            S_LATCH_LO: begin st <= S_RAM_HI; end                                   // rd registers the lo word this edge
            S_RAM_HI:   begin vlo <= $signed(rd); raddr <= raddr_of(ch, hh, age_hi, p_hi); st <= S_LATCH_HI; end
            S_LATCH_HI: begin st <= S_MAC_A; end
            S_MAC_A: begin                                     // MAC m: operands into the multiplier's input registers
                if (m == 2'd0) vhi <= $signed(rd);             // (only on the first MAC after the fetch)
                a_r <= use_hi ? (m == 2'd0 ? $signed(rd) : vhi) : vlo;
                b_r <= negate ? ((BUG == 2) ? c2 : -c2) : coef_sel;          // Helix's MADD64(sum, vHi, -c2)
                st <= S_MAC_B;
            end
            S_MAC_B: begin prod <= a_r * b_r; st <= S_MAC_C; end
            S_MAC_C: begin
                if (to_acc2) acc2 <= acc2 + prod; else acc1 <= acc1 + prod;
                if (m == nmac_m1[1:0]) st <= S_NEXT; else begin m <= m + 2'd1; st <= S_MAC_A; end
            end
            S_NEXT: begin
                m <= 2'd0;
                if (x != 3'd7) begin x <= x + 3'd1; st <= S_TAPS; end
                else st <= S_STORE;
            end
            S_STORE: begin
                x <= 3'd0;
                if (g0) begin
                    if (ch) outbuf1[0] <= clip16(acc1); else outbuf0[0] <= clip16(acc1);
                end else if (g16) begin
                    if (ch) outbuf1[16] <= clip16(acc1); else outbuf0[16] <= clip16(acc1);
                end else begin
                    if (ch) begin outbuf1[grp - 5'd1] <= clip16(acc1); outbuf1[5'd1 - grp] <= clip16(acc2); end
                    else    begin outbuf0[grp - 5'd1] <= clip16(acc1); outbuf0[5'd1 - grp] <= clip16(acc2); end
                end
                acc1 <= RND; acc2 <= RND;
                if (grp == 5'd16) begin
                    grp <= 5'd0;
                    if (ch) st <= S_DONE; else begin ch <= 1'b1; st <= S_TAPS; end
                end else begin grp <= grp + 5'd1; st <= S_TAPS; end
            end
            S_CLR: begin                                       // zeroing writes ring[zaddr] this cycle
                zaddr <= zaddr + 10'd1;
                if (zaddr == 10'd1023) begin zeroing <= 1'b0; busy_r <= 1'b0; st <= S_IDLE; end
            end
            S_DONE: begin busy_r <= 1'b0; pc <= 7'd0; slots_done <= slots_done + 16'd1; st <= S_IDLE; end
            default: st <= S_IDLE;
            endcase
        end
    end
endmodule
